"""Chapter spec for tools/2x/build2x.py. Order = chain order; #next is derived from it.

Edit ops (see build2x.apply_edits): drop_step, drop_from, insert_before, insert_after, prepend, append,
replace, replace_nth, delete_lines, sub, cond, insert_stock. Anchors are exact stripped line texts,
('text', nth) for the nth match, or 're:<regex>'."""
GROUP='RestedXP Alliance 2x Druid'
COND='NightElf Druid'
FILE_HEADER='''-- RestedXP 2x route for a Night Elf Druid (ChromieCraft, WotLK 3.3.5a, 2x XP).
-- GENERATED by tools/2x/build2x.py from the stock 3.3.5 chapters listed in each block's
-- "Source:" comment, with the edits in tools/2x/spec2x.py. Edit the spec, not this file.
local faction = UnitFactionGroup("player")
if faction == "Horde" then return end'''

TELEPORT = """step << Druid
#completewith next
.cast 18960 >> |cRXP_WARN_Cast|r |T135758:0|t[Teleport: Moonglade]
.usespell 18960
.zoneskip Moonglade"""

def LOGANAAR(text):
    return """step << Druid
.goto Moonglade,52.53,40.57
>>Talk to |cRXP_FRIENDLY_Loganaar|r
.trainer >> %s
.target Loganaar""" % text

def EXPERT_RIDING(zone, x, y, npc):
    return """step << Druid
.goto %s,%s,%s
>>Talk to |cRXP_FRIENDLY_%s|r
.money <250
.istrained 34090
.train 34090 >> Train Expert Riding (250g). Flight Form needs it. Skip this if you cannot afford it yet, the guide asks again later
.target %s""" % (zone, x, y, npc, npc)

def FLIGHT_FORM(zone, x, y, npc, extra=''):
    return """step << Druid
.goto %s,%s,%s
>>Talk to |cRXP_FRIENDLY_%s|r
.istrained 33943
.skill riding,<225,1
.train 33943 >> Train Flight Form (needs Expert Riding)
.target %s%s""" % (zone, x, y, npc, npc, extra)

SPEC=[
 dict(src='1-6 Shadowglen', name='1-7 Shadowglen (2x)', file='Alliance-Teldrassil-2x.lua'),
 dict(src='6-11 Teldrassil', name='7-12 Teldrassil (2x)', file='Alliance-Teldrassil-2x.lua', edits=[
    # Heeding the Call: Kal's breadcrumb to Mathrengyl (needs level 10, free XP). Stock skips it because
    # a 1x character is 9 on the last Kal visit; at 2x with rested XP you are usually 10 already
    ('insert_after', ('.trainer >> Train your level 8 spells', 4), """step << Druid
.goto Teldrassil,55.9,61.6
>>Talk to |cRXP_FRIENDLY_Kal|r
.accept 5923 >> Accept Heeding the Call (only offered from level 10, skip if you are not 10 yet)
.target Kal
.xp <10,1"""),
    ('replace', '.accept 5921 >> Accept Moonglade', '.turnin -5923 >> Turn in Heeding the Call\n    .accept 5921 >> Accept Moonglade'),
    # Tears of the Moon (2518) needs The Temple of the Moon (2519), a breadcrumb from Sister Aquinne; stock never takes it
    ('replace_nth', '.accept 2518 >> Accept Tears of the Moon', 1, '.turnin -2519 >> Turn in The Temple of the Moon\n    .accept 2518 >> Accept Tears of the Moon'),
    ('insert_before', ('.accept 2518 >> Accept Tears of the Moon', 0), """step
    .goto Darnassus,28.9,45.8
>>Talk to |cRXP_FRIENDLY_Sister Aquinne|r in the Temple Gardens
    .accept 2519 >> Accept The Temple of the Moon
.target Sister Aquinne"""),
    ('replace_nth', '.accept 2518 >> Accept Tears of the Moon', 0, '.turnin 2519 >> Turn in The Temple of the Moon\n    .accept 2518 >> Accept Tears of the Moon'),
 ]),
 dict(src='11-14 Darkshore', name='12-14 Darkshore (2x)', file='Alliance-Darkshore-2x.lua', edits=[
    # the accept of The Fragments Within only exists in the 1x branch
    ('replace', '.turnin 4813 >> Turn in The Fragments Within', '.turnin -4813 >> Turn in The Fragments Within'),
    # Bear Form first: Lunaclaw's cave is just east of Auberdine. Do it before the beach loop, turn Body and
    # Heart in at Darnassus via Moonglade and fly back from Moonglade, keeping the hearthstone for later
    ('drop_step', '.use 15208 >>Use the Cenarion Moondust inside the cave, defeat Lunaclaw and speak with his spirit after'),
    ('drop_step', '.fly Teldrassil>> Fly to Teldrassil'),
    ('drop_step', '.turnin 6001 >> Turn in Body and Heart'),
    ('insert_after', '.home >> Set your Hearthstone to Auberdine', """step << Druid
    .isOnQuest 6001
    .goto Darkshore,43.5,45.9
    .use 15208 >>Bear Form first: go to the cave just east of town, use the Cenarion Moondust inside, defeat Lunaclaw and speak with his spirit after
    .complete 6001,1 --Defeat Lunaclaw (x1)
step << Druid
    .isOnQuest 6001
    #completewith next
    .cast 18960 >> |cRXP_WARN_Cast|r |T135758:0|t[Teleport: Moonglade]
    .usespell 18960
    .zoneskip Moonglade
step << Druid
    .isOnQuest 6001
    #sticky
    #completewith next
    .goto Moonglade,44.1,45.2
    .fly Teldrassil>> Fly to Rut'theran Village and take the portal up to Darnassus
step << Druid
    .isOnQuest 6001
    .goto Darnassus,35.375,8.405
.target Mathrengyl Bearwalker
>>Talk to |cRXP_FRIENDLY_Mathrengyl Bearwalker|r
    .turnin 6001 >> Turn in Body and Heart (Bear Form)
    .trainer >> Train your class spells
step << Druid
    #completewith next
    .cast 18960 >> |cRXP_WARN_Cast|r |T135758:0|t[Teleport: Moonglade] again
    .usespell 18960
    .zoneskip Moonglade
step << Druid
    .goto Moonglade,48.1,67.2
    .fly Auberdine >> Fly back to Auberdine
    .zoneskip Darkshore"""),
 ]),
 dict(src='14-20 Bloodmyst', name='14-23 Bloodmyst (2x)', file='Alliance-Darkshore-2x.lua', edits=[
    # Aquatic Form chain (A Lesson to Learn -> Trial of the Lake -> Trial of the Sea Lion) still exists in 3.3.5
    ('replace', '.accept 26 >> Accept A Lesson to Learn << tbc', '.accept 26 >> Accept A Lesson to Learn'),
    ('replace', '.turnin 26 >> Turn in A Lesson to Learn << tbc', '.turnin 26 >> Turn in A Lesson to Learn'),
    ('replace', '.accept 29 >> Accept Trial of the Lake << tbc', '.accept 29 >> Accept Trial of the Lake'),
    ('sub', r'^(\s*)step << Druid tbc\s*$', r'\1step << Druid'),
    # Alien Predators (9634) needs Coming of Age/Elekks Are Serious Business from Azure Watch and the Exodar, not on the route
    ('delete_lines', r'^\.accept 9634 >> Accept Alien Predators$'),
    ('drop_step', '.complete 9634,1 --Kill Bloodmyst Hatchling (x10)'),
    ('drop_step', '.turnin 9634 >> Turn in Alien Predators << !Paladin'),
    # Cat Form (20): you are ~22 when the Lessons Anew chain brings you to Darnassus
    ('insert_after', '.accept 6121 >> Accept Lessons Anew', """step << Druid
.goto Darnassus,35.375,8.405
>>Talk to |cRXP_FRIENDLY_Mathrengyl Bearwalker|r
.trainer >> Train your class spells. Cat Form is available from level 20
.target Mathrengyl Bearwalker"""),
 ]),
 dict(src='20-21 Darkshore', name='23-23 Darkshore (2x)', file='Alliance-Darkshore-2x.lua', edits=[
    ('sub', r'^(\s*)step << Druid tbc\s*$', r'\1step << Druid'),   # Darkshore half of the Aquatic Form pendant
    # Researching the Corruption (1275) needs The Corruption Abroad from Stormwind, which the route visits only later
    ('drop_step', '.accept 1275 >> Accept Researching the Corruption'),
 ]),
 dict(src='21-23 Ashenvale', name='23-25 Ashenvale (2x)', file='Alliance-Darkshore-2x.lua', edits=[
    ('drop_step', '.complete 1275,1'),   # Researching the Corruption is no longer accepted (see the Darkshore chapter)
    ('drop_step', '.turnin 1275 >> Turn in Researching the Corruption'),
 ]),
 dict(src='24-27 Redridge/Duskwood', name='25-29 Redridge/Duskwood (2x)', file='Alliance-EasternKingdoms-2x.lua', edits=[
    ('sub', r'^(\s*)step << Druid tbc\s*$', r'\1step << Druid'),   # Westfall pendant half, Moonglade combine, Aquatic Form turn-in
 ]),
 dict(src='28-30 Duskwood', name='29-32 Duskwood (2x)', file='Alliance-EasternKingdoms-2x.lua', edits=[
    ('replace', '.turnin 269 >> Turn in Seeking Wisdom', '.turnin -269 >> Turn in Seeking Wisdom'),   # already turned in at the end of the Redridge/Duskwood chapter
    # Mudrock Soup and Bugs (Theramore, STV chapter) needs the Morgan Stern breadcrumb from Angus Stern in Stormwind (level 33)
    ('insert_before', '.zone Ironforge >> Take the tram to Ironforge', """step
    .goto Stormwind City,51.8,93.6
>>Talk to |cRXP_FRIENDLY_Angus Stern|r in the Blue Recluse (Mage Quarter). Needs level 33, skip if you are not there yet
    .accept 1260 >> Accept Morgan Stern
.target Angus Stern
    .xp <33,1"""),
    # Travel Form (30) at Moonglade, then the Darnassus mount trip from Rut'theran instead of the Stormwind boat
    ('cond', '.skill riding,75 >> Take the boat to Darkshore then to Darnassus and buy your mount. Then hearth back to Stormwind', 'NightElf !Druid wotlk'),
    ('insert_before', '.skill riding,75 >> Take the boat to Darkshore then to Darnassus and buy your mount. Then hearth back to Stormwind',
     TELEPORT + "\n" + LOGANAAR('Train your class spells. Travel Form is available from level 30') + """
step << Druid
#completewith next
.goto Moonglade,44.1,45.2
.fly Teldrassil >> Fly to Rut'theran Village, then take the portal up to Darnassus
step << Druid
.goto Darnassus,38.1,15.3
.money <5.00
.skill riding,75 >> Buy Apprentice Riding and a mount from Lelanai in Darnassus
step << Druid
#completewith next
.hs >> Hearth back to Stormwind"""),
 ]),
 dict(src='30-32 Hillsbrad', name='32-35 Hillsbrad (2x)', file='Alliance-EasternKingdoms-2x.lua'),
 dict(src='32-33 Shimmering Flats', name='35-37 Shimmering Flats (2x)', file='Alliance-STV-Dustwallow-2x.lua', cleanup=[1142], edits=[
    # Defias in Dustwallow? (11137) needs A Disturbing Development (11136), only reachable in the Dustwallow chapter
    ('drop_step', '.accept 11137 >> Accept Defias in Dustwallow?'),
    # the stock chapter hands off to Hillsbrad/Arathi; we go straight to the STV chapter, which starts in Theramore
    ('append', """step
.goto Tanaris,51.006,29.345
.fly Theramore >> Fly to Theramore
.zoneskip Dustwallow Marsh"""),
 ]),
 dict(src='35-37 STV', name='37-41 STV (2x)', file='Alliance-STV-Dustwallow-2x.lua', cleanup=[193, 196, 543, 602], edits=[
    ('replace_nth', '.unitscan Garn Mathers', 0, '.unitscan Garn Mathers\n.isOnQuest 11137'),   # 11137 is accepted in the Dustwallow chapter
    ('replace', '.accept 1204 >> Accept Mudrock Soup and Bugs', '.turnin -1260 >> Turn in Morgan Stern\n.accept 1204 >> Accept Mudrock Soup and Bugs'),
    # Kurzen's Mystery (207) needs Colonel Kurzen (202, an elite kill the route skips)
    ('drop_step', '.accept 207 >> Accept Kurzen\'s Mystery'),
    ('drop_step', '.complete 207,1'), ('drop_step', '.complete 207,4'), ('drop_step', '.complete 207,3'), ('drop_step', '.complete 207,2'),
    ('drop_step', '.turnin 207 >> Turn in Kurzen\'s Mystery'),
 ]),
 dict(src='37-39 Dustwallow', name='41-44 Dustwallow (2x)', file='Alliance-STV-Dustwallow-2x.lua', cleanup=[1106, 11149], edits=[
    # A Disturbing Development (11136) -> Defias in Dustwallow? (11137) -> Renn McGill chain; stock skipped the first two accepts
    ('insert_after', '.turnin 11134 >> Turn in The End of the Deserters', """step
.goto Dustwallow Marsh,65.07,47.13
>>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Aden|r in the keep
.accept 11136 >> Accept A Disturbing Development
.target Lieutenant Aden"""),
    ('insert_before', ('.unitscan Garn Mathers', 0), """step
.goto Dustwallow Marsh,59.658,41.106
>>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Wymor|r at Sentry Point
.turnin 11136 >> Turn in A Disturbing Development
.accept 11137 >> Accept Defias in Dustwallow?
.target Captain Wymor"""),
    # Corrosion Prevention (11174) needs The Zeppelin Crash from Tabetha's farm, which the route reaches after the crash
    ('delete_lines', r'^\.accept 11174 >> Accept Corrosion Prevention$'),
    ('drop_step', '.complete 11174,1'),
    ('delete_lines', r'^\.turnin 11174 >> Turn in Corrosion Prevention$'),
    # Dire Bear Form (40) on the way back to Theramore
    ('insert_before', ('.isOnQuest 1204,1222,11138,1206,11181', 2), TELEPORT + "\n" + LOGANAAR('Train your class spells. Dire Bear Form is available from level 40')),
 ]),
 dict(src='39-42 Arathi Highlands', name='44-45 Arathi Highlands (2x)', file='Alliance-STV-Dustwallow-2x.lua', cleanup=[707, 1360]),
 dict(src='43-46 STV part 2', name='45-47 STV part 2 (2x)', file='Alliance-STV-Dustwallow-2x.lua', edits=[
    ('sub', r'\b8551\b', '614'),   # 8551 is the Horde version of The Captain's Chest; 614 is the Alliance one
 ]),
 dict(src='47-49 Tanaris', name='47-53 Tanaris (2x)', file='Alliance-Tanaris-Ungoro-2x.lua', cleanup=[162, 3022], edits=[
    # the stock 47-49 chapter assumes the accepts and Wastewander quests of the 1x-only "45-45 Tanaris" chapter
    ('insert_stock', '45-45 Tanaris', '.fly Tanaris>> Fly to Tanaris', '.turnin 1707 >> Turn in Water Pouch Bounty', 'prepend'),
 ]),
 dict(src='50-51 Searing Gorge', name='53-55 Searing Gorge (2x)', file='Alliance-Tanaris-Ungoro-2x.lua', cleanup=[3378], edits=[
    # we arrive by boat at Menethil Harbor, not from The Hinterlands
    ('replace', '.goto The Hinterlands,11.071,46.153', '.goto Wetlands,9.490,59.693'),
    ('replace', '.target Guthrum Thunderfist', '.target Shellei Brondir'),
    ('replace', '>>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guthrum Thunderfist|r', '>>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei Brondir|r'),
 ]),
 dict(src='51-52 Burning Steppes', name='55-57 Burning Steppes (2x)', file='Alliance-Tanaris-Ungoro-2x.lua', cleanup=[3368, 4808], edits=[
    ('drop_step', '.accept 4512 >> Accept A Little Slime Goes a Long Way'),   # Felwood chapter is skipped
    ('append', """step
.goto Ironforge,55.5,47.7
.fly Wetlands >> Fly to Menethil Harbor
.zoneskip Wetlands
.zoneskip Dustwallow Marsh
.zoneskip Tanaris
step
.goto Wetlands,5.075,63.408
.zone Dustwallow Marsh >> Take the boat to Theramore
.zoneskip Dustwallow Marsh
.zoneskip Tanaris
step
.goto Dustwallow Marsh,67.476,51.300
.fly Tanaris >> Fly to Gadgetzan
.zoneskip Tanaris"""),
 ]),
 dict(src="53-54 Un'Goro Crater", name="57-59 Un'Goro Crater (2x)", file='Alliance-Tanaris-Ungoro-2x.lua', cleanup=[980, 3908], edits=[
    ('replace', '.turnin 4493 >> Turn in March of the Silithid', '.turnin -4493 >> Turn in March of the Silithid'),   # Felwood chapter is skipped
    # the Darnassus tail (Calm Before the Storm, Felbound Ancients, cloth) belongs to the skipped Felwood flow; go to Stormwind via Jaina instead
    ('drop_step', ('.accept 4508 >> Accept Calm Before the Storm', 1)),
    ('delete_lines', r'^\.accept 4508 >> Accept Calm Before the Storm$'),
    ('drop_from', '.hs >> Hearth to Darnassus'),
    ('append', """step
.goto Tanaris,51.006,29.345
.fly Theramore >> Fly to Theramore
.zoneskip Dustwallow Marsh
.zoneskip Stormwind City"""),
    ('insert_stock', '45-45 Tanaris', '.accept 11222 >> Accept Proof of Treachery', '.turnin 11222 >> Turn in Warn Bolvar!', 'append'),
    ('delete_lines', r'^\.accept 11223 >> Accept Return to Jaina$'),
    ('append', """step
.zone Stormwind City >> If Jaina cannot teleport you, take the boat from Theramore to Menethil Harbor and fly to Stormwind
.zoneskip Stormwind City"""),
 ]),
 dict(src='59-61 Hellfire Peninsula', name='59-65 Hellfire Peninsula (2x)', file='Alliance-Outland-2x.lua', edits=[
    # Hellfire quests need level 58; the sim arrives at 59 at 2x, this only grinds if you are behind
    ('prepend', """step
.xp 58 >> Grind to level 58 before going through the Dark Portal (Hellfire quests need it). This completes on its own if you are already 58"""),
    # Expert Riding (60) at the Honor Hold riding trainer, retried on a later Honor Hold visit
    ('insert_after', ('.hs >> Hearth to Honor Hold', 0), EXPERT_RIDING('Hellfire Peninsula', 54.28, 62.69, 'Hargen Bronzewing')),
    ('insert_after', ('.hs >> Hearth to Honor Hold', 2), EXPERT_RIDING('Hellfire Peninsula', 54.28, 62.69, 'Hargen Bronzewing')),
    # Flight Form at the stock training trip (Darnassus or Moonglade)
    ('insert_after', ('.goto Darnassus,35.375,8.405', 1), FLIGHT_FORM('Darnassus', 35.375, 8.405, 'Mathrengyl Bearwalker', '\n.zoneskip Darnassus,1')),
    ('insert_after', '.goto Moonglade,52.53,40.57', FLIGHT_FORM('Moonglade', 52.53, 40.57, 'Loganaar', '\n.zoneskip Darnassus')),
 ]),
 dict(src='61-63 Zangarmarsh', name='65-68 Zangarmarsh (2x)', file='Alliance-Outland-2x.lua', cleanup=[9801], edits=[
    ('insert_after', ('.train 27001,1 << Druid', 1), FLIGHT_FORM('StormwindClassic', 20.893, 55.463, 'Sheldras Moontree')),
 ]),
 dict(src='63-64 Terokkar Forest', name='68-70 Terokkar Forest (2x)', file='Alliance-Outland-2x.lua', cleanup=[10917]),
 dict(src='64-65 Nagrand', name='70-72 Nagrand (2x)', file='Alliance-Outland-2x.lua', cleanup=[10253], edits=[
    ('insert_after', ('.train 26980,1 << Druid', 1), FLIGHT_FORM('StormwindClassic', 20.893, 55.463, 'Sheldras Moontree')),
    # the chapter ends in Stormwind; the next chapter takes the Stormwind boat, no need to hearth to Shattrath
    ('drop_step', ('.hs >> Hearth to Shattrath', 0)),
    ('drop_step', ('.hs >> Hearth to Shattrath', 0)),
 ]),
 dict(src='70-72 Northrend', name='72-75 Borean Tundra/Howling Fjord (2x)', file='Alliance-Northrend-2x.lua', edits=[
    ('insert_after', '.home Valiance Keep >> Set your Hearthstone to Valiance Keep',
     EXPERT_RIDING('Borean Tundra', 58.94, 68.18, 'Maigra Keenfeather') + """
step << Druid
#completewith next
.istrained 33943
.skill riding,<225,1
.cast 18960 >> |cRXP_WARN_Cast|r |T135758:0|t[Teleport: Moonglade]
.usespell 18960
.zoneskip Moonglade
""" + FLIGHT_FORM('Moonglade', 52.53, 40.57, 'Loganaar') + """
step << Druid
#completewith next
.zoneskip Moonglade,1
.hs >> Hearth back to Valiance Keep"""),
 ]),
 dict(src='72-74 Northrend', name='75-78 Howling Fjord/Dragonblight (2x)', file='Alliance-Northrend-2x.lua', edits=[
    # Rifle the Bodies (12000) gates Prevent the Accord and the rest of the Stars' Rest hub; it needs "Your Presence is
    # Required at Stars' Rest" from Emissary Skyhaven at Moa'ki Harbor. Go Valiance Keep -> Unu'pe -> coast road -> Moa'ki first
    ('drop_step', '>>Go northeast to Dragonblight'),
    ('insert_before', '.accept 12000 >> Accept Rifle the Bodies', """step
.goto Borean Tundra,59.0,68.3
.fly Unu'pe, Borean Tundra >> Fly to Unu'pe
.zoneskip Dragonblight
step
#completewith next
.goto Borean Tundra,78.5,73.5,60,0
.goto Dragonblight,40.0,79.0,60,0
.goto Dragonblight,48.06,74.96
>>Ride east along the south coast into Dragonblight to Moa'ki Harbor
.zoneskip Dragonblight
step
.goto Dragonblight,48.06,74.96
.target Emissary Skyhaven
.accept 11995 >> Accept Your Presence is Required at Stars' Rest
.fp Moa'ki, Dragonblight >> Get the Moa'ki flight path
step
#completewith next
.goto Dragonblight,29,55.5
>>Ride northwest to Stars' Rest"""),
    ('replace', '.accept 12000 >> Accept Rifle the Bodies', '.turnin 11995 >> Turn in Your Presence is Required at Stars\' Rest\n.accept 12000 >> Accept Rifle the Bodies'),
 ]),
 dict(src='74-76 Northrend', name='78-80 Dragonblight/Grizzly Hills (2x)', file='Alliance-Northrend-2x.lua', edits=[
    ('insert_after', '.fp Dalaran >> Get the Dalaran flight path', EXPERT_RIDING('Dalaran', 69.76, 45.43, 'Hira Snowdawn') + """
step
.goto Dalaran,69.76,45.43
>>Talk to |cRXP_FRIENDLY_Hira Snowdawn|r at Krasus' Landing
.money <1000
.istrained 54197
.train 54197 >> Train Cold Weather Flying (1000g) so you can use Flight Form in Northrend
.target Hira Snowdawn"""),
 ]),
 dict(src='76-78 Northrend', name="80 Zul'Drak/Sholazar (2x)", file='Alliance-Northrend-2x.lua', cleanup=[12533, 12534, 12569, 12654, 12803]),
]
