-- GENERATED by tools/5x/build5x.py from Guides/7x/Alliance-Borean-7x.lua; edit the 7x file or the script.
-- RestedXP 5x route: Borean Tundra (WotLK 3.3.5a, Whitemane 5x). Arrive at Valiance Keep at 68
-- by the Stormwind Harbor boat. This is the stock 3.3.5 "70-72 Northrend" Borean route
-- (Valiance Keep, Farshire, Riplash, D.E.H.T.A., the Honored Ancestors, Amber Ledge,
-- Coldarra, Fizzcrank Airstrip, Unu'pe, Thassarian at En'kilah) reused nearly verbatim,
-- because every quest here is level 71-72 and pays full value until 76-77. At 5x the chapter
-- ends around 75, before anything decays. Cut after the
-- Fizzcrank Airstrip hand-ins around 77: the Winterfin, snobold, Bixie and sinkhole tails
-- would pay 60-80% and Dragonblight pays more. No Auction House step, no level-71 wait.
local faction = UnitFactionGroup("player")
if faction == "Horde" then return end

RXPGuides.RegisterGuide([[
#wotlk
<< Alliance
#name 68-75 Borean Tundra (5x)
#version 1
#group RestedXP Alliance 5x
#next 75-77 Dragonblight (5x)
step
    #sticky
    #completewith next
    +Borean Tundra at 5x: you arrive at 68 and leave for Dragonblight around 75. Valiance Keep has every Alliance class trainer inside the keep, train there before you start and again whenever you hearth back. The route is the stock one: Valiance Keep, Farshire, Riplash, D.E.H.T.A., Amber Ledge, Coldarra, Fizzcrank Airstrip, Unu'pe and En'kilah
step
    .goto Borean Tundra,57.8,68.0
    >>The class trainers stand inside the keep building
    .trainer >> Train your class spells
step
.goto Borean Tundra,59,68.3
.target Tomas Riverwell
.fp Valiance Keep, Borean Tundra >> Get the Valiance Keep flight path
step
.home Valiance Keep >> Set your Hearthstone to Valiance Keep
step
.goto Borean Tundra,57.8,67.6
.target Recruitment Officer Blythe
.accept 11672 >> Accept Enlistment Day
step
.goto Borean Tundra,56.7,72.6
.target General Arlos
.turnin 11672 >> Turn in Enlistment Day
.accept 11727 >> Accept A Time for Heroes
step
.goto Borean Tundra,56.4,69.6
.target Sergeant Hammerhill
.turnin 11727 >> Turn in A Time for Heroes
.accept 11797 >> Accept The Siege
step
.goto Borean Tundra,55,68.9
.target Medic Hawthorn
.accept 11789 >> Accept A Soldier in Need
step
.goto Borean Tundra,54.4,69.6
.complete 11797,1
.mob Crypt Crawler
>>Kill Crypt Crawler
step
.goto Borean Tundra,56.4,69.6
.target Sergeant Hammerhill
.turnin 11797 >> Turn in The Siege
.accept 11889 >> Accept Death From Above
step
.goto Borean Tundra,57.5,69.3
>>Click the First Aid Supplies - It's a small brown chest, downstairs in this ship, next to a candle shrine
.complete 11789,1
>>Collect Hawthorn's Anti-Venom
step
.goto Borean Tundra,57.5,69.1
>>Click the Cultist Shrine - It looks like a small candle shrine on the ground downstairs in this ship, next to the wall
.accept 11920 >> Accept Cultists Among Us
step
.goto Borean Tundra,57.8,69.2
.target Captain "Lefty" Lugsail
.turnin 11920 >> Turn in Cultists Among Us
step
.goto Borean Tundra,57.8,69.2
.target Admiral Cantlebree
.accept 11791 >> Accept Notify Arlos
step
.goto Borean Tundra,56.7,72.6
.target General Arlos
.turnin 11791 >> Turn in Notify Arlos
step
.goto Borean Tundra,56.7,72.6
.target Counselor Talbot
.accept 12141 >> Accept A Diplomatic Mission
step
.goto Borean Tundra,56.6,72.5
.target Harbinger Vurenn
.accept 11792 >> Accept Enemies of the Light
step
.goto Borean Tundra,55,68.9
.target Medic Hawthorn
.turnin 11789 >> Turn in A Soldier in Need
step
.goto Borean Tundra,55,70.5
.use 35278
>>Use your Reinforced Net on Scourged Flamespitters flying next to the fortress wall
.complete 11889,1
.mob Scourged Flamespitter
>>Kill Scourged Flamespitter
step
.goto Borean Tundra,56.4,69.6
.target Sergeant Hammerhill
.turnin 11889 >> Turn in Death From Above
.accept 11897 >> Accept Plug the Sinkholes
step
.goto Borean Tundra,50.9,72.1
.use 35704
>>Click your Incendiary Explosives
.complete 11897,1
>>Set the Explosive at the Southern Sinkhole
step
.goto Borean Tundra,54.1,63.7
.use 35704
>>Click your Incendiary Explosives
.complete 11897,2
>>Set the Explosives at the Northern Sinkhole
step
.goto Borean Tundra,53.7,60.1
.mob Cultist Necrolytes
>>Kill Cultist Necrolytes
.complete 11792,1
>>Collect Cultist Communique
step
.goto Borean Tundra,56.4,69.6
.target Sergeant Hammerhill
.turnin 11897 >> Turn in Plug the Sinkholes
.accept 11928 >> Accept Farshire
step
.goto Borean Tundra,56.8,69.5
.target Mark Hanes
.accept 11927 >> Accept Word on the Street
step
.goto Borean Tundra,56.6,72.5
.target Harbinger Vurenn
.turnin 11792 >> Turn in Enemies of the Light
.accept 11793 >> Accept Further Investigation
step
.goto Borean Tundra,58.7,68.4
.target Leryssa
.turnin 11927 >> Turn in Word on the Street
.accept 11599 >> Accept Thassarian, My Brother
step
.goto Borean Tundra,58.6,67.3
.target Vindicator Yaala
.turnin 11793 >> Turn in Further Investigation
.accept 11794 >> Accept The Hunt is On
step
.goto Borean Tundra,58.6,67.1
.use 35125
>>Use your Oculus of the Exorcist on "Salty" John Thorpe
.target "Salty" John Thorpe
>>Tell him you have reason to believe he is involved in cultist activity
.mob "Salty" John Thorpe
>>Kill "Salty" John Thorpe
.complete 11794,3
>>Defeat the Cultist in the kitchen
step
.goto Borean Tundra,58.8,68.7
.target Airman Skyhopper
.accept 11707 >> Accept Distress Call
step
.goto Borean Tundra,59.2,68.3
.use 35125
>>Use your Oculus of the Exorcist on Tom Hegger
.target Tom Hegger
>>Ask him about the Cult of the Damed
.mob Tom Hegger
>>Kill Tom Hegger
.complete 11794,1
>>Defeat the Cultist on the docks
step
.goto Borean Tundra,56.7,71.8
.use 35125
>>Use your Oculus of the Exorcist on Guard Mitchells
.target Guard Mitchells
>>Ask him how long he has worked for the Cult of the Damned
.mob Guard Mitchells
>>Kill Guard Mitchells
.complete 11794,2
>>Defeat the Cultist in the jail
step
.goto Borean Tundra,58.6,67.3
.target Vindicator Yaala
.turnin 11794 >> Turn in The Hunt is On
step
.goto Borean Tundra,58.2,62.8
.target Gerald Green
.turnin 11928 >> Turn in Farshire
.accept 11901 >> Accept Military?  What Military?
step
.goto Borean Tundra,56.8,55.6
>>Go inside the mine to 56.8,55.6
>>Click the Plagued Grain - Inside the mine, it looks like a bag full of grain, next to a wheel barrow
.turnin 11901 >> Turn in Military? What Military?
.accept 11902 >> Accept Pernicious Evidence
step
.goto Borean Tundra,56,55.4
.target William Allerton
.turnin 11599 >> Turn in Thassarian, My Brother
.accept 11600 >> Accept The Late William Allerton
step
.goto Borean Tundra,58.2,62.8
.target Gerald Green
.turnin 11902 >> Turn in Pernicious Evidence
.accept 11903 >> Accept It's Time for Action
step
.goto Borean Tundra,58.3,62.8
.target Wendy Darren
.accept 11913 >> Accept Take No Chances
step
.goto Borean Tundra,58.2,63
.target Jeremiah Hawning
.accept 11908 >> Accept Reference Material
step
.goto Borean Tundra,57,61.7
.complete 11903,1
.mob Plagued Scavenger
>>Kill Plagued Scavenger
.use 35491
>>Use Wendy's Torch next to Farshire Grain bags
.complete 11913,1
>>Burn 8 Farshire Grain
step
.goto Borean Tundra,55.8,58.3
>>Click Fields, Factories and Workshops - It's a little red book lying inside the burning house
.complete 11908,1
>>Collect Fields, Factories and Workshops
step
.goto Borean Tundra,58.3,62.8
.target Wendy Darren
.turnin 11913 >> Turn in Take No Chances
step
.goto Borean Tundra,58.2,62.8
.target Gerald Green
.turnin 11903 >> Turn in It's Time for Action
.accept 11904 >> Accept Fruits of Our Labor
step
.goto Borean Tundra,58.2,63
.target Jeremiah Hawning
.turnin 11908 >> Turn in Reference Material
.accept 12035 >> Accept Repurposed Technology
step
.goto Borean Tundra,58.1,61.1
.mob Harvest Collectors
>>Kill Harvest Collectors
.use 35943
>>Use Jeremiahs Tools on their corpses
.complete 12035,1
>>Rewire 5 Harvest Collectors
step
.goto Borean Tundra,57.9,53.4
>>Go inside the cave to 57.9,53.4
.mob Captain Jacobs
>>Kill Captain Jacobs
.collect 35705,1,11904 >> Collect 1 Cart Release Key
step
.goto Borean Tundra,57.2,54.6
>>Click the Cart Release switch - It's a switch on the side of a cart with blue ore inside of it
.complete 11904,1
>>Release the Ore Cart
step
.goto Borean Tundra,58.2,62.8
>>Go outside to 58.2,62.8
.target Gerald Green
.turnin 11904 >> Turn in Fruits of Our Labor
.accept 11962 >> Accept One Last Delivery
step
.goto Borean Tundra,58.2,63
.target Jeremiah Hawning
.turnin 12035 >> Turn in Repurposed Technology
step
.goto Borean Tundra,57.3,66.6
.target Hilda Stoneforge
.turnin 11962 >> Turn in One Last Delivery
.accept 11963 >> Accept Weapons for Farshire
step
.goto Borean Tundra,58.7,68.4
.target Leryssa
.turnin 11600 >> Turn in The Late William Allerton
.accept 11601 >> Accept Lost and Found
step
.goto Borean Tundra,58.3,68
.target James Deacon
.turnin 11601 >> Turn in Lost and Found
.accept 11603 >> Accept In Wine, Truth
step
.goto Borean Tundra,58.2,62.8
.target Gerald Green
.turnin 11963 >> Turn in Weapons for Farshire
.accept 11965 >> Accept Call to Arms!
step
.goto Borean Tundra,57.3,59.4
>>Click the Bell Rope - It's a huge rope hanging up the stairs in the stairwell of the town hall building
.complete 11965,1
>>Ring the Farshire Bell
step
.goto Borean Tundra,58.2,62.8
.target Gerald Green
.turnin 11965 >> Turn in Call to Arms!
step
.goto Borean Tundra,61.9,65.7
>>Go underwater to 61.9,65.7
>>Click the Wine Crate underwater in the broken ship
.complete 11603,1
>>Collect Kul Tiras Wine
step
.goto Borean Tundra,58.5,68.1
.target Old Man Colburn
.turnin 11603 >> Turn in In Wine, Truth
.accept 11604 >> Accept A Deserter
step
.goto Borean Tundra,56.7,71.5
.target Private Brau
.turnin 11604 >> Turn in A Deserter
.accept 11932 >> Accept Cowards and Fools
step
.goto Borean Tundra,58.4,67.8
.target Midge
.accept 11575 >> Accept Nick of Time
step
.goto Borean Tundra,47.1,75.5
.target Karuk
.turnin 12141 >> Turn in A Diplomatic Mission
.accept 11613 >> Accept Karuk's Oath
step
.goto Borean Tundra,46.5,77.2
.complete 11613,1
.mob Skadir Raider
>>Kill Skadir Raider
.complete 11613,2
.mob Skadir Longboatsman
>>Kill Skadir Longboatsman
step
.goto Borean Tundra,44.2,77.8
>>Kill the Riplash Myrmidon and cheering Skadir mobs
.target Captured Tuskarr Prisoner
.accept 12471 >> Accept Cruelty of the Kvaldir
step
.goto Borean Tundra,47.1,75.5
.target Karuk
.turnin 11613 >> Turn in Karuk's Oath
.accept 11619 >> Accept Gamel the Cruel
.turnin 12471 >> Turn in Cruelty of the Kvaldir
step
.goto Borean Tundra,46.4,78.2
>>Go inside the cave to 46.4,78.2
.complete 11619,1
.mob Gamel the Cruel
>>Kill Gamel the Cruel
step
.goto Borean Tundra,47.1,75.5
.target Karuk
.turnin 11619 >> Turn in Gamel the Cruel
.accept 11620 >> Accept A Father's Words
step
.goto Borean Tundra,43.6,80.5
.target Veehja
.turnin 11620 >> Turn in A Father's Words
.accept 11625 >> Accept The Trident of Naz'jan
step
.goto Borean Tundra,54.7,89.1
>>Go into the big building to 54.7,89.1
.mob Ragnar Drakkarlund
>>Kill Ragnar Drakkarlund
.complete 11625,1
>>Collect Trident of Naz'jan
step
.goto Borean Tundra,43.6,80.5
.target Veehja
.turnin 11625 >> Turn in The Trident of Naz'jan
.accept 11626 >> Accept The Emissary
step
.goto Borean Tundra,52.2,88.2
>>Swim underwater to the bubbling rock at the very bottom, so you don't run out of air
.use 35850
>>Use your Trident of Naz'jan on Leviroth
.complete 11626,1
.mob Leviroth
>>Kill Leviroth
step
.goto Borean Tundra,47.1,75.5
.target Karuk
.turnin 11626 >> Turn in The Emissary
step
.goto Borean Tundra,57,44.3
.target Arch Druid Lathorius
.accept 11864 >> Accept A Mission Statement
.turnin 11864 >> Turn in A Mission Statement
.accept 11866 >> Accept Ears of Our Enemies
.accept 11876 >> Accept Help Those That Cannot Help Themselves
step
.goto Borean Tundra,57.3,44.1
.target Hierophant Cenius
.accept 11869 >> Accept Happy as a Clam
step
.goto Borean Tundra,57,44
>>He walks around the small pond in the middle of the camp
.target Killinger the Den Watcher
.accept 11884 >> Accept Ned, Lord of Rhinos...
step
.goto Borean Tundra,56.8,44
.target Zaza
.accept 11865 >> Accept Unfit for Death
step
.goto Borean Tundra,53.8,40.6
.use 35228
>>Use your D.E.H.T.A. Trap Smasher while standing next to Trapped Mammoth Calves
.complete 11876,1
>>Free 8 Mammoth Calves
step
.goto Borean Tundra,53.4,42.7
.complete 11869,1
.mob Loot Crazed Diver
>>Kill Loot Crazed Diver
.mob Loot Crazed Divers
>>Kill Loot Crazed Divers
.complete 11866,1
>>Collect Nesingwary Lackey Ear
step
.goto Borean Tundra,46.4,40
.complete 11884,2
>>Find and kill "Lunchbox"
.complete 11884,1
.mob Nedar, Lord of Rhinos
>>Kill Nedar, Lord of Rhinos
step
.goto Borean Tundra,56.2,50.5
>>Stand inside the Caribou Traps on the ground - They look like metal spiked traps on the ground
.use 35127
>>Use your Pile of Fake Furs
.complete 11865,1
>>Trap 8 Nesingwary Trappers
step
+Make sure you don't have Animal Blood on you. If you do, go for a swim to wash it off, before approaching the druids
step
.goto Borean Tundra,57,44.3
.target Arch Druid Lathorius
.turnin 11866 >> Turn in Ears of Our Enemies
.turnin 11876 >> Turn in Help Those That Cannot Help Themselves
.accept 11878 >> Accept Khu'nok Will Know
step
.goto Borean Tundra,57.3,44.1
.target Hierophant Cenius
.turnin 11869 >> Turn in Happy as a Clam
.accept 11870 >> Accept The Abandoned Reach
step
.goto Borean Tundra,57,44
>>He walks around the small pond in the middle of the camp
.target Killinger the Den Watcher
.turnin 11884 >> Turn in Ned, Lord of Rhinos...
step
.goto Borean Tundra,56.8,44
.target Zaza
.turnin 11865 >> Turn in Unfit for Death
.accept 11868 >> Accept The Culler Cometh
step
.goto Borean Tundra,59.5,30.4
>>Deliver the Orphaned Mammoth Calf to Khu'nok
.target Khu'nok the Behemoth
.turnin 11878 >> Turn in Khu'nok Will Know
.accept 11879 >> Accept Kaw the Mammoth Destroyer
step
>>Ride around and find a Wooly Mammoth Bull
.vehicle
>>Click it to ride it
step
.goto Borean Tundra,53.7,23.9
>>Go north on the Wooly Mammoth Bull to 53.7,23.9
>>Use the skills on your mammoth action bar to do the following:
.mob Kaw the Mammoth Destroyer
>>Kill Kaw the Mammoth Destroyer
>>Click Kaw's War Halberd on the ground
.complete 11879,1
>>Collect Kaw's War Halberd
step
.goto Borean Tundra,57,44.3
.target Arch Druid Lathorius
.turnin 11879 >> Turn in Kaw the Mammoth Destroyer
step
.goto Borean Tundra,57.3,56.5
.complete 11868,1
.mob Karen "I Don't Caribou" the Culler
>>Kill Karen "I Don't Caribou" the Culler
step
.goto Borean Tundra,57.8,55.1
.target Hierophant Liandra
.turnin 11870 >> Turn in The Abandoned Reach
.accept 11871 >> Accept Not On Our Watch
step
.goto Borean Tundra,59.1,55.9
.mob Northsea Thugs
>>Kill Northsea Thugs
>>Click the Shipment of Animal Parts containers on the ground - They look like brown bags and crates sitting on the ground around this area
.complete 11871,1
>>Collect Shipment of Animal Parts
step
.goto Borean Tundra,57.8,55.1
.target Hierophant Liandra
.turnin 11871 >> Turn in Not On Our Watch
.accept 11872 >> Accept The Nefarious Clam Master...
step
.goto Borean Tundra,61.5,66.5
.complete 11872,1
.mob Clam Master K
>>Kill Clam Master K
step
.goto Borean Tundra,57.3,44.1
.target Hierophant Cenius
.turnin 11872 >> Turn in The Nefarious Clam Master...
step
.goto Borean Tundra,56.8,44
.target Zaza
.turnin 11868 >> Turn in The Culler Cometh
step
.goto Borean Tundra,54.3,36.1
.target Etaruk
.accept 11612 >> Accept Reclaiming the Quarry
step
.goto Borean Tundra,54.7,35.8
.target Elder Atkanok
.accept 11605 >> Accept The Honored Ancestors
step
.goto Borean Tundra,54.4,35.1
.complete 11612,1
.mob Beryl Treasure Hunter
>>Kill Beryl Treasure Hunter
step
.goto Borean Tundra,52.8,34
>>Click the Elder Sagani - It looks like 2 small totem pole things at the base of the big stone on the huge bone cart
.complete 11605,2
>>Identify the Elder Sagani
step
.goto Borean Tundra,52.3,31.2
>>Click the Elder Takret - It looks like 2 small totem pole things at the base of the big stone on the huge bone cart
.complete 11605,3
>>Identify the Elder Takret
step
.goto Borean Tundra,50.9,32.4
>>Click the Elder Kesuk - It looks like 2 small totem pole things at the base of the big stone on the huge bone cart
.complete 11605,1
>>Identify the Elder Kesuk
step
.goto Borean Tundra,54.7,35.8
.target Elder Atkanok
.turnin 11605 >> Turn in The Honored Ancestors
.accept 11607 >> Accept The Lost Spirits
step
.goto Borean Tundra,54.3,36.1
.target Etaruk
.turnin 11612 >> Turn in Reclaiming the Quarry
.accept 11617 >> Accept Hampering Their Escape
step
.goto Borean Tundra,51.5,31.4
.mob Beryl Hounds
>>Kill Beryl Hounds
>>Collect Cores of Malice
.use 34711
>>Use the Cores of Malice on Kaskala Craftsmen and Kaskala Shaman
.complete 11607,1
>>Free 3 Kaskala Craftsman spirits
.complete 11607,2
>>Free 3 Kaskala Shaman spirits
step
>>Kill Beryl Reclaimers all around this area:
.collect 34772,3,11617 >> Collect 3 Gnomish Grenade
step
.goto Borean Tundra,52.2,32.1
.use 34772
>>Use your Gnomish Grenade while standing under the floating platform
.complete 11617,2
>>Destroy the North Platform
step
.goto Borean Tundra,51,33.9
.use 34772
>>Use your Gnomish Grenade while standing under the floating platform
.complete 11617,3
>>Destroy the West Platform
step
.goto Borean Tundra,52.8,34.5
.use 34772
>>Use your Gnomish Grenade while standing under the floating platform
.complete 11617,1
>>Destroy the East Platform
step
.goto Borean Tundra,54.7,35.8
.target Elder Atkanok
.turnin 11607 >> Turn in The Lost Spirits
.accept 11609 >> Accept Picking Up the Pieces
step
.goto Borean Tundra,54.3,36.1
.target Etaruk
.turnin 11617 >> Turn in Hampering Their Escape
.accept 11623 >> Accept A Visit to the Curator
step
.goto Borean Tundra,53.1,33.3
>>Click the Tuskarr Ritual Objects - They look like small stone fish and blue smoking bowls on the ground around this area
.complete 11609,1
>>Collect Tuskarr Ritual Object
step
.goto Borean Tundra,50.1,32.6
>>Go up the hill to 50.1,32.6
.complete 11623,1
.mob Curator Insivius
>>Kill Curator Insivius
step
.goto Borean Tundra,54.7,35.8
.target Elder Atkanok
.turnin 11609 >> Turn in Picking Up the Pieces
.accept 11610 >> Accept Leading the Ancestors Home
step
.goto Borean Tundra,54.3,36.1
.target Etaruk
.turnin 11623 >> Turn in A Visit to the Curator
step
.goto Borean Tundra,52.8,34
.use 34715
>>Use your Tuskarr Ritual Object while standing next to the Elder Sagani
.complete 11610,2
>>Complete Elder Sagani's ceremony
step
.goto Borean Tundra,52.3,31.2
.use 34715
>>Use your Tuskarr Ritual Object while standing next to the Elder Takret
.complete 11610,3
>>Complete Elder Takret's ceremony
step
.goto Borean Tundra,50.9,32.4
.use 34715
>>Use your Tuskarr Ritual Object while standing next to the Elder Kesuk
.complete 11610,1
>>Complete Elder Kesuk's ceremony
step
.goto Borean Tundra,54.7,35.8
.target Elder Atkanok
.turnin 11610 >> Turn in Leading the Ancestors Home
step
.goto Borean Tundra,45.3,34.5
.target Surristrasz
.fp Amber Ledge, Borean Tundra >> Get the Amber Ledge flight path
step
.goto Borean Tundra,45.3,33.3
.target Librarian Donathan
.turnin 11575 >> Turn in Nick of Time
.accept 11587 >> Accept Prison Break
step
.goto Borean Tundra,45,33.4
.target Librarian Garren
.accept 11576 >> Accept Monitoring the Rift: Cleftcliff Anomaly
step
#sticky
.goto Borean Tundra,40.5,39.2
.mob Beryl Mage Hunters
>>Kill Beryl Mage Hunters
.collect 34688,1,11587 >> Collect 1 Beryl Prison Key
>>Click an Arcane Prison
.complete 11587,1
>>Free an Arcane Prisoner
step
.goto Borean Tundra,41.2,41.8
.goto Borean Tundra,41.2,41.8,0.5
>>The path down to Monitoring the Rift: Cleftcliff Anomaly starts here
step
.goto Borean Tundra,34.3,42
.use 34669
>>Use your Arcanometer in this spot next to the purple glowing crack in the ground
.complete 11576,1
>>Take the Cleftcliff Anomaly Reading
step
.goto Borean Tundra,45,33.4
.target Librarian Garren
.turnin 11576 >> Turn in Monitoring the Rift: Cleftcliff Anomaly
.accept 11582 >> Accept Monitoring the Rift: Sundered Chasm
step
.goto Borean Tundra,45.3,33.3
.target Librarian Donathan
.turnin 11587 >> Turn in Prison Break
.accept 11590 >> Accept Abduction
step
.goto Borean Tundra,46.8,29.3
.goto Borean Tundra,46.8,29.3,0.5
>>The path down to Monitoring the Rift: Sundered Chasm starts here
step
.goto Borean Tundra,44,28.6
>>Go down the path and underwater to 44,28.6
.use 34669
>>Use your Arcanometer next to the huge purple glowing crack underwater
.complete 11582,1
>>Take the Sundered Chasm Reading
step
.goto Borean Tundra,45,33.4
.target Librarian Garren
.turnin 11582 >> Turn in Monitoring the Rift: Sundered Chasm
.accept 12728 >> Accept Monitoring the Rift: Winterfin Cavern
step
.goto Borean Tundra,46.8,29.3
.goto Borean Tundra,46.8,29.3,0.5
>>The path down to Monitoring the Rift: Winterfin Cavern starts here
step
.goto Borean Tundra,40.1,19.7
>>Stand in the mouth of the cave, past the torches
.use 34669
>>Use your Arcanometer
.complete 12728,1
>>Take the Winterfin Cavern Reading
step
.goto Borean Tundra,45,33.4
.target Librarian Garren
.turnin 12728 >> Turn in Monitoring the Rift: Winterfin Cavern
step
.goto Borean Tundra,43.5,37.4
>>Fight a Beryl Sorcerer
.use 34691
>>Use your Arcane Binder on him when you see the 'Beryl Sorcerer can now be captured' message in your chat
.complete 11590,1
>>Capture a Beryl Sorcerer
step
.goto Borean Tundra,45.3,33.3
.target Librarian Donathan
.turnin 11590 >> Turn in Abduction
.accept 11646 >> Accept The Borean Inquisition
step
.goto Borean Tundra,46.3,32.8
>>Go inside the tall tower to 46.3,32.8
.target Librarian Normantis
.turnin 11646 >> Turn in The Borean Inquisition
.accept 11648 >> Accept The Art of Persuasion
step
.use 34811
>>Use your Neural Needler on the Imprisoned Beryl Sorcerer repeatedly to Interrogate the Prisoner
.complete 11648,1
>>Interrogate the Prisoner
step
.goto Borean Tundra,46.3,32.8
.target Librarian Normantis
.turnin 11648 >> Turn in The Art of Persuasion
.accept 11663 >> Accept Sharing Intelligence
step
.goto Borean Tundra,45.3,33.3
>>Go outside the tower to 45.3,33.3
.target Librarian Donathan
.turnin 11663 >> Turn in Sharing Intelligence
.accept 11671 >> Accept A Race Against Time
step
.goto Borean Tundra,42.1,39.5
.use 34897
>>Use your Beryl Shield Detonator inside the big blue glowing circle
.mob Inquisitor Salrand
>>Kill Inquisitor Salrand
>>Click Salrand's Lockbox
.complete 11671,1
>>Collect Salrand's Broken Key
step
.goto Borean Tundra,45.3,33.3
.target Librarian Donathan
.turnin 11671 >> Turn in A Race Against Time
.accept 11679 >> Accept Reforging the Key
step
.goto Borean Tundra,45.3,34.5
.target Surristrasz
.turnin 11679 >> Turn in Reforging the Key
.accept 11680 >> Accept Taking Wing
step
.goto Borean Tundra,46.4,37.3
.target Warmage Anzim
.turnin 11680 >> Turn in Taking Wing
.accept 11681 >> Accept Rescuing Evanor
step
.goto Borean Tundra,46.4,32.6,0.3
>>Watch the cutscene, then you'll get teleported back to Amber Ledge
step
.goto Borean Tundra,46.4,32.4
.target Archmage Evanor
.turnin 11681 >> Turn in Rescuing Evanor
.accept 11682 >> Accept Dragonspeak
step
.goto Borean Tundra,45.3,34.5
>>Go outside the tower to 45.3,34.5
.target Surristrasz
.turnin 11682 >> Turn in Dragonspeak
.accept 11733 >> Accept Traversing the Rift
step
.goto Borean Tundra,45.3,34.5
.target Surristrasz
.fly Transitus Shield, Coldarra >> Fly to Transitus Shield, Coldarra
>>Fly to Transitus Shield, Coldarra
step
.goto Borean Tundra,32.9,34.4
.target Archmage Berinand
.turnin 11733 >> Turn in Traversing the Rift
.accept 11900 >> Accept Reading the Meters
.accept 11910 >> Accept Secrets of the Ancients
step
.goto Borean Tundra,33.3,34.5
.target Raelorasz
.accept 11918 >> Accept Basic Training
step
.goto Borean Tundra,33.5,34.4
.target Librarian Serrah
.accept 11912 >> Accept Nuts for Berries
step
.goto Borean Tundra,35,28
.mob Coldarra Spellbinders
>>Kill Coldarra Spellbinders
>>Collect Scintillating Fragment
.use 35648
>>Click the Scintillating Fragment in your bags
.accept 11941 >> Accept Puzzling...
step
.goto Borean Tundra,28.3,28.5
>>Click the Coldarra Geological Monitor - It looks like a blue sphere on the ground at the base of the building
.complete 11900,1
>>Take the Nexus Geological Reading
step
.goto Borean Tundra,31.7,20.6
>>Click the Coldarra Geological Monitor - It looks like a blue sphere on the ground in the entrance of the building
.complete 11900,3
>>Take the Northern Coldarra Reading
step
.goto Borean Tundra,22.6,23.5
>>Click the Coldarra Geological Monitor - It looks like a blue sphere on the ground in the entrance of the building
.complete 11900,4
>>Take the Western Coldarra Reading
step
.goto Borean Tundra,28.3,35
>>Click the Coldarra Geological Monitor - It looks like a blue sphere on the ground in the entrance of the building
.complete 11900,2
>>Take the Southern Coldarra Reading
step
.complete 11918,1
.mob Coldarra Spellweaver
>>Kill Coldarra Spellweaver
.mob Glacial Ancient
>>Kill Glacial Ancient
.complete 11910,1
>>Collect Glacial Splinter
.skill herbalism,<1,1
>>Herbalism
.mob Magic-Bound Ancient
>>Kill Magic-Bound Ancient
.complete 11910,2
>>Collect Magic-Bound Splinter
>>Click Frostberry Bushes
.complete 11912,1
>>Collect Frostberry
step
.goto Borean Tundra,32.9,34.4
.target Archmage Berinand
.turnin 11900 >> Turn in Reading the Meters
.turnin 11910 >> Turn in Secrets of the Ancients
step
.goto Borean Tundra,33.3,34.5
.target Raelorasz
.turnin 11918 >> Turn in Basic Training
.accept 11936 >> Accept Hatching a Plan
.turnin 11941 >> Turn in Puzzling...
.accept 11943 >> Accept The Cell
step
.goto Borean Tundra,33.5,34.4
.target Librarian Serrah
.turnin 11912 >> Turn in Nuts for Berries
.accept 11914 >> Accept Keep the Secret Safe
step
+As you do the following steps:
.mob Coldarra Wyrmkin
>>Kill Coldarra Wyrmkin
>>Collect Frozen Axe
>>Skip to the next step in the guide
step
.goto Borean Tundra,24.1,29.6
.mob Warbringer Goredrak
>>Kill Warbringer Goredrak
.complete 11943,1
>>Collect Energy Core
step
.goto Borean Tundra,27.3,20.5
.mob General Cerulean
>>Kill General Cerulean
.complete 11943,2
>>Collect Prison Casing
step
.collect 35586,5,11936
>>Make sure you have 5 Frozen Axes
step
.goto Borean Tundra,27.8,24.2
.mob Arcane Serpents
>>Kill Arcane Serpents
.complete 11914,1
>>Collect Nexus Mana Essence
>>Click Blue Dragon Eggs - They look like big eggs with blue crystals on them on the ground
.complete 11936,1
>>Destroy 5 Dragon Eggs
step
.goto Borean Tundra,33.3,34.5
.target Raelorasz
.turnin 11936 >> Turn in Hatching a Plan
.accept 11919 >> Accept Drake Hunt
.turnin 11943 >> Turn in The Cell
step
.goto Borean Tundra,33.5,34.4
.target Librarian Serrah
.turnin 11914 >> Turn in Keep the Secret Safe
step
.goto Borean Tundra,24.6,27.1
.use 35506
>>Use your Raelorasz's Spear on a Nexus Drake Hatchling
.complete 11919,1
>>Do not kill it, let it hit you until it becomes friendly
step
.goto Borean Tundra,33.3,34.5
.complete 11919,1
>>Capture the Nexus Drake
.target Raelorasz
.turnin 11919 >> Turn in Drake Hunt
.accept 11931 >> Accept Cracking the Code
step
.use 35671
>>Use the Augmented Arcane Prison in your bags
.target Keristrasza
.accept 11946 >> Accept Keristrasza
.turnin 11946 >> Turn in Keristrasza
.accept 11951 >> Accept Bait and Switch
step
.goto Borean Tundra,32.7,29
.mob Coldarra Spellbinders
>>Kill Coldarra Spellbinders
.complete 11931,1
>>Collect Shimmering Rune
step
.goto Borean Tundra,32.7,27.8
.mob Inquisitor Caleras
>>Kill Inquisitor Caleras
.complete 11931,2
>>Collect Azure Codex
step
>>Wander all around and do the following:
>>Click Crystallized Mana on the ground - They look like pink crystals
.complete 11951,1
>>Collect Crystallized Mana Shard
step
.use 35671
>>Use the Augmented Arcane Prison in your bags
.target Keristrasza
.turnin 11951 >> Turn in Bait and Switch
.accept 11957 >> Accept Saragosa's End
step
.use 35671
>>Use the Augmented Arcane Prison in your bags
.target Keristrasza
.goto Borean Tundra,21.2,22.5,0.5
>>Tell her you are ready to face Saragosa
step
>>She teleports you to a platform
.use 35690
>>Click the Arcane Power Focus in your bags
>>Wait for Saragosa to appear and become human
.mob Saragosa
>>Kill Saragosa
.complete 11957,1
>>Collect Saragosa's Corpse
step
.use 35671
>>Use the Augmented Arcane Prison in your bags
.target Keristrasza
.turnin 11957 >> Turn in Saragosa's End
.accept 11967 >> Accept Mustering the Reds
step
.goto Borean Tundra,33.3,34.5
.target Raelorasz
.turnin 11931 >> Turn in Cracking the Code
.turnin 11967 >> Turn in Mustering the Reds
.accept 11969 >> Accept Springing the Trap
step
.goto Borean Tundra,25.4,21.7
.use 44950
>>Use Raelorasz' Spark next to the Signal Fire
>>Watch the cutscene
.complete 11969,1
>>Lure Malygos
step
.goto Borean Tundra,33.3,34.5
.target Raelorasz
.turnin 11969 >> Turn in Springing the Trap
step
.fly Amber Ledge, Borean Tundra >> Fly to Amber Ledge
>>Fly to Amber Ledge
step
.goto Borean Tundra,56.6,20.1
.target Kara Thricestar
.fp Fizzcrank Airstrip, Borean Tundra >> Get the Fizzcrank Airstrip flight path
step
.home Fizzcrank Airstrip >> Set your Hearthstone to Fizzcrank Airstrip
step
.goto Borean Tundra,57,18.7
.target Fizzcrank Fullthrottle
.turnin 11707 >> Turn in Distress Call
.accept 11708 >> Accept The Mechagnomes
.target Fizzcrank Fullthrottle
.complete 11708,1
>>Listen to Fizzcrank Fullthrottle's tale
step
.goto Borean Tundra,57.4,18.7
.target Jinky Wingnut
.turnin 11708 >> Turn in The Mechagnomes
.accept 11712 >> Accept Re-Cursive
step
.goto Borean Tundra,57.4,18.7
.target Mordle Cogspinner
.accept 11710 >> Accept What's the Matter with the Transmatter?
.accept 11704 >> Accept King Mrgl-Mrgl
step
.goto Borean Tundra,57.6,18.7
.target Crafty Wobblesprocket
.accept 11645 >> Accept Dirty, Stinkin' Snobolds!
step
.goto Borean Tundra,53.1,13.5
>>Click Crafty's Stuff - They look like wooden crates on the ground around this area
.complete 11645,1
>>Collect Crafty's Stuff
step
.goto Borean Tundra,54,13.5
.goto Borean Tundra,54,13.5,0.3
>>The path down to Bonker Togglevolt starts here
step
.goto Borean Tundra,55.6,12.6
>>Go inside the cave to 55.6,12.6
.target Bonker Togglevolt
.accept 11673 >> Accept Get Me Outa Here!
.complete 11673,1
>>Escort Bonker Togglevolt to safety
step
.goto Borean Tundra,57,18.7
>>Go outside the cave to 57,18.7
.target Fizzcrank Fullthrottle
.turnin 11673 >> Turn in Get Me Outa Here!
step
.goto Borean Tundra,57.6,18.7
.target Crafty Wobblesprout
.turnin 11645 >> Turn in Dirty, Stinkin' Snobolds!
.accept 11650 >> Accept Just a Few More Things...
step
.goto Borean Tundra,58.5,17.6
.mob Fizzcrank Mechagnomes
>>Kill Fizzcrank Mechagnomes
.use 34973
>>Use the Re-Cursive Transmatter Injection on their corpses
.complete 11712,1
>>Curse & port 6 Fizzcrank Gnomes
>>Click Fizzcrank Spare Parts
.complete 11710,1
>>Collect Fizzcrank Spare Parts
.skill engineering,<1,1
>>Engineering
step
.goto Borean Tundra,58.5,17.6
.mob mechanical mobs
>>Kill mechanical mobs
>>Collect The Ultrasonic Screwdriver
.use 34984
>>Click The Ultrasonic Screwdriver
.accept 11729 >> Accept The Ultrasonic Screwdriver
step
.goto Borean Tundra,57.6,18.7
.target Crafty Wobblesprout
.turnin 11729 >> Turn in The Ultrasonic Screwdriver
.accept 11730 >> Accept Master and Servant
step
.goto Borean Tundra,57.4,18.7
.target Mordle Cogspinner
.turnin 11710 >> Turn in What's the Matter with the Transmatter?
.accept 11692 >> Accept Check in With Bixie
step
.goto Borean Tundra,57.4,18.7
.target Jinky Wingnut
.turnin 11712 >> Turn in Re-Cursive
.accept 11788 >> Accept Lefty Loosey, Righty Tighty
step
.goto Borean Tundra,57,18.7
.target Fizzcrank Fullthrottle
.accept 11725 >> Accept Finding Pilot Tailspin
step
.goto Borean Tundra,58.7,18.5
.mob robots in this area
>>Kill robots in this area
.use 35116
>>Use the Ultrasonic Screwdriver on their corpses
.complete 11730,1
>>Reprogram 15 Robots
step
.goto Borean Tundra,60.2,20.4
>>Click the West Point Station Valve - It looks like a red round handle on the side of the metal pipe
.complete 11788,1
.mob Twonky
>>Kill Twonky
step
.goto Borean Tundra,65.4,17.4
>>Click the North Point Station Valve - It looks like a red round handle on the side of the metal pipe
.complete 11788,2
.mob ED-210
>>Kill ED-210
step
.goto Borean Tundra,63.7,22.5
>>Click the Mid Point Station Valve - It looks like a red round handle on the side of the metal pipe
.complete 11788,3
.mob Max Blasto
>>Kill Max Blasto
step
.goto Borean Tundra,64.4,23.1
>>Click Crafty's Tools - It looks like a small chest, next to some steel beams on the ground
.complete 11650,1
>>Collect Crafty's Tools
step
.goto Borean Tundra,65.2,28.8
>>Click the South Point Station Valve - It looks like a red round handle ont he side of the metal pipe
.complete 11788,4
.mob The Grinder
>>Kill The Grinder
step
.goto Borean Tundra,61.7,35.8
.target Iggy "Tailspin" Cogtoggle
.turnin 11725 >> Turn in Finding Pilot Tailspin
.accept 11726 >> Accept A Little Bit of Spice
step
.goto Borean Tundra,61.1,44.6
.mob Gorlocs
>>Kill Gorlocs
.complete 11726,1
>>Collect Gorloc Spice Pouch
step
.goto Borean Tundra,61.7,35.8
.target Iggy "Tailspin" Cogtoggle
.turnin 11726 >> Turn in A Little Bit of Spice
.accept 11728 >> Accept Lupus Pupus
step
>>All around this area:
.use 35121
>>Use your Wolf Bait on Oil-stained Wolves around this area
>>Click the Wolf Droppings that spawn
.complete 11728,1
>>Collect Microfilm
step
.goto Borean Tundra,61.7,35.8
.target Iggy "Tailspin" Cogtoggle
.turnin 11728 >> Turn in Lupus Pupus
.accept 11795 >> Accept Emergency Protocol: Section 8.2, Paragraph C
step
.goto Borean Tundra,61,37.8
.target Fizzcrank Recon Pilots
>>Search their bodies for their Insignia
.complete 11795,1
>>Collect Fizzcrank Pilot's Insignia
step
.goto Borean Tundra,61.7,35.8
.target Iggy "Tailspin" Cogtoggle
.turnin 11795 >> Turn in Emergency Protocol: Section 8.2, Paragraph C
.accept 11796 >> Accept Emergency Protocol: Section 8.2, Paragraph D
step
.goto Borean Tundra,59.7,39.2
.use 35224
>>Use your Emergency Torch next to the crashed plane
.complete 11796,2
>>Scuttle a Southern Wreck
step
.goto Borean Tundra,63.3,37
.use 35224
>>Use your Emergency Torch next to the crashed plane
.complete 11796,1
>>Scuttle a Eastern Wreck
step
.goto Borean Tundra,60.9,33.7
.use 35224
>>Use your Emergency Torch next to the crashed plane
.complete 11796,3
>>Scuttle a Northwestern Wreck
step
.goto Borean Tundra,61.7,35.8
.target Iggy "Tailspin" Cogtoggle
.turnin 11796 >> Turn in Emergency Protocol: Section 8.2, Paragraph D
.accept 11873 >> Accept Give Fizzcrank the News
step
.goto Borean Tundra,63.8,46.1
.target Ataika
.turnin 11932 >> Turn in Cowards and Fools
.accept 12086 >> Accept The Son of Karkut
.accept 11949 >> Accept Not Without a Fight!
step
.goto Borean Tundra,64,45.7
.target Utaik
.accept 11945 >> Accept Preparing for the Worst
step
.goto Borean Tundra,65.3,47.2
.complete 11949,1
.mob Kvaldir Raider
>>Kill Kvaldir Raider
>>Click Kaskala Supplies baskets - They look like wooden baskets on the ground
.complete 11945,1
>>Collect Kaskala Supplies
step
.goto Borean Tundra,63.8,46.1
.target Ataika
.turnin 11949 >> Turn in Not Without a Fight!
.accept 11950 >> Accept Muahit's Wisdom
step
.goto Borean Tundra,64,45.7
.target Utaik
.turnin 11945 >> Turn in Preparing for the Worst
step
.goto Borean Tundra,67.2,54.9
.target Elder Muahit
.turnin 11950 >> Turn in Muahit's Wisdom
.accept 11961 >> Accept Spirits Watch Over Us
step
.goto Borean Tundra,67.7,50.4
>>Click Iruk's body - His body is floating underwater
>>Search his corpse
.complete 11961,1
>>Collect Issliruk's Totem
step
.goto Borean Tundra,67.2,54.9
.target Elder Muahit
.turnin 11961 >> Turn in Spirits Watch Over Us
.accept 11968 >> Accept The Tides Turn
step
.goto Borean Tundra,67.4,56.8
.complete 11968,1
.mob Heigarr the Horrible
>>Kill Heigarr the Horrible
step
.goto Borean Tundra,67.2,54.9
.target Elder Muahit
.turnin 11968 >> Turn in The Tides Turn
step
.goto Borean Tundra,67.2,54.9
.target Hotawa
.accept 12117 >> Accept Travel to Moa'ki Harbor
step
.goto Borean Tundra,82,46.4
.target Corporal Venn
.turnin 12086 >> Turn in The Son of Karkut
.accept 11944 >> Accept Surrounded!
step
.goto Borean Tundra,82,46.4
.target Private Casey
.accept 12157 >> Accept The Lost Courier
step
.goto Borean Tundra,81.5,42.5
.mob Rocknar
>>Kill Rocknar
.complete 11650,3
>>Collect A Handful of Rocknar's Grit
step
.goto Borean Tundra,82.2,44.8
.complete 11944,1
.mob Ziggurat Defender
>>Kill Ziggurat Defender
step
.goto Borean Tundra,82,46.4
.target Corporal Venn
.turnin 11944 >> Turn in Surrounded!
.accept 12088 >> Accept Thassarian, the Death Knight
step
.goto Borean Tundra,84.8,41.7
.target Thassarian
.turnin 12088 >> Turn in Thassarian, the Death Knight
.accept 11956 >> Accept Finding the Phylactery
step
.goto Borean Tundra,82.4,46.6
.vehicle
>>Click Dusk to ride him - He is a skeletal death knight mount with hooves that glow blue
step
.goto Borean Tundra,85.4,33.3
>>Click the Frozen Phylactery - It looks like a green canister with a purple top underwater
>>Kill Phylactery Guardian that spawns
.complete 11956,1
>>Collect Tanathal's Phylactery
step
.goto Borean Tundra,84.8,41.7
.target Thassarian
.turnin 11956 >> Turn in Finding the Phylactery
.accept 11938 >> Accept Buying Some Time
step
.goto Borean Tundra,84.4,31.4
.complete 11938,1
.mob En'kilah mob
>>Kill En'kilah mob
step
.goto Borean Tundra,84.8,41.7
.target Thassarian
.turnin 11938 >> Turn in Buying Some Time
.accept 11942 >> Accept Words of Power
step
.goto Borean Tundra,89.4,28.9
>>Kill 2 bug guards and kill the 2 cocoons next to High Priest Talet-Kha
.mob High Priest Talet-Kha
>>Kill High Priest Talet-Kha
.complete 11942,3
>>Collect High Priest Talet-Kha's Scroll
step
.goto Borean Tundra,88.1,20.9
.mob High Priest Andorath
>>Kill High Priest Andorath
.complete 11942,1
>>Collect High Priest Andorath's Scroll
step
.goto Borean Tundra,83.9,20.5
>>Kill the 3 guards
.mob High Priest Naferset
>>Kill High Priest Naferset
.complete 11942,2
>>Collect High Priest Naferset's Scroll
step
.goto Borean Tundra,84.8,41.7
.target Thassarian
.turnin 11942 >> Turn in Words of Power
step
.goto Borean Tundra,57.1,18.8,1
.hs >> Hearth to Fizzcrank Airstrip
>>Hearth to Fizzcrank Airstrip
step
.goto Borean Tundra,57,18.7
.target Fizzcrank Fullthrottle
.turnin 11873 >> Turn in Give Fizzcrank the News
step
.goto Borean Tundra,57.4,18.7
.target Jinky Wingnut
.turnin 11788 >> Turn in Lefty Loosey, Righty Tighty
step
.goto Borean Tundra,57.6,18.7
.target Crafty Wobblesprocket
.turnin 11650 >> Turn in Just a Few More Things...
.turnin 11730 >> Turn in Master and Servant
step
    >>Clean up before leaving Borean Tundra. These only show if the quest is still in your log
    .abandon 11692 >> Abandon Check in With Bixie
    .abandon 11704 >> Abandon King Mrgl-Mrgl
    .abandon 11725 >> Abandon Finding Pilot Tailspin
    .abandon 11645 >> Abandon Dirty, Stinkin' Snobolds!
    .abandon 11650 >> Abandon Just a Few More Things...
    .abandon 11730 >> Abandon Master and Servant
    .abandon 11788 >> Abandon Lefty Loosey, Righty Tighty
    .abandon 12157 >> Abandon The Lost Courier
step
    #sticky
    #completewith next
    +Borean is done around 77. Keep Travel to Moa'ki Harbor in your log, the Dragonblight chapter starts by handing it in there. Fly to Unu'pe and ride east along the coast road into Dragonblight
step
    .goto Borean Tundra,57.1,18.8
    .fly Unu'pe >> Fly to Unu'pe
]])
