-- RestedXP 5x route: Grizzly Hills (WotLK 3.3.5a, Whitemane Frostmourne 5x). Arrive from
-- Dragonblight around 77-78 by road from Wyrmrest Temple through Wintergarde Keep. Stock 3.3.5
-- "74-76 Northrend" Grizzly Hills steps reused nearly verbatim (Amberpine Lodge, Zeb'Halak/Drakuru,
-- Silverbrook, Vordrassil, Westfall Brigade, Drakil'jin, Dun Argol): every quest here is level
-- 74-75 and pays full value to 80. The stock `.xp 76` wait and the Dalaran detour are dropped.
-- GENERATED by tools/5x/build5x.py, edit the script instead.
local faction = UnitFactionGroup("player")
if faction == "Horde" then return end

RXPGuides.RegisterGuide([[
#wotlk
<< Alliance
#name 77-80 Grizzly Hills (5x)
#version 1
#group RestedXP Alliance 5x
step
    #sticky
    #completewith next
    +Grizzly Hills at 5x: you arrive at Wintergarde Keep around 77-78 and hit 80 in Grizzly Hills. The route is the stock one: Amberpine Lodge, the Drakuru troll chain in the north-west, Silverbrook, Vordrassil, then the Westfall Brigade camp and the Thor Modan iron dwarves in the east. No class trainers in the zone. Dalaran has them all plus Cold Weather Flying (77, 1000g): from Wyrmrest Temple ride north into Crystalsong Forest to the Violet Stand (15.7,42.5) and take the teleport crystal up, then fly back once you have the Dalaran flight path
step
.goto Dragonblight,77.1,50.1
.target Gryphon Commander Urik
.accept 12511 >> Accept The Hills Have Us
step
.goto Grizzly Hills,31.3,59.1
.target Vana Grey
.fp Amberpine Lodge, Grizzly Hills >> Get the Amberpine Lodge flight path
step
.goto Grizzly Hills,31.8,59.6
>>Click the Amberseed - It's a small bucket with seeds in it, to left as you enter the door, under the stairs
.accept 12225 >> Accept Mmm... Amberseeds!
step
.goto Grizzly Hills,31.8,60.2
.target Lieutenant Dumont
.turnin 12511 >> Turn in The Hills Have Us
.accept 12292 >> Accept Local Support
step
.goto Grizzly Hills,32.1,60
.target Master Woodsman Anderhol
.turnin 12225 >> Turn in Mmm... Amberseeds!
.accept 12226 >> Accept Just Passing Through
.accept 12212 >> Accept Replenishing the Storehouse
.accept 12215 >> Accept Them or Us!
step
.home Amberpine Lodge >> Set your Hearthstone to Amberpine Lodge
step
.goto Grizzly Hills,33.3,58
.mob Tallhorn Stags
>>Kill Tallhorn Stags
.complete 12212,1
>>Collect Succulent Venison
step
.goto Grizzly Hills,32.1,60
.target Master Woodsman Anderhol
.turnin 12212 >> Turn in Replenishing the Storehouse
.accept 12216 >> Accept Take Their Rear!
step
.goto Grizzly Hills,31.8,60.2
.target Lieutenant Dumont
.accept 12210 >> Accept Troll Season!
step
.goto Grizzly Hills,30.6,53.4
>>Click the Blackroot plants - They look like grassy plants on the ground around this area
.complete 12226,1
>>Collect Blackroot Stalk
.mob Grizzly Bears
>>Kill Grizzly Bears
.complete 12216,1
>>Collect Grizzly Flank
step
.goto Grizzly Hills,32.1,60
.target Master Woodsman Anderhol
.turnin 12216 >> Turn in Take Their Rear!
.turnin 12226 >> Turn in Just Passing Through
.accept 12227 >> Accept Doing Your Duty
step
.goto Grizzly Hills,32.2,58.9
>>Click the Amberpine Outhouse - It looks like a wooden outhouse
>>Use the outhouse
.complete 12227,1
>>Collect Partially Processed Amberseeds
step
.goto Grizzly Hills,32.1,60
.target Master Woodsman Anderhol
.turnin 12227 >> Turn in Doing Your Duty
step
.goto Grizzly Hills,26,67.4
.complete 12215,1
.mob Graymist Hunter
>>Kill Graymist Hunter
step
.goto Grizzly Hills,15.9,65.3
>>Click the Cedar Chest - It's a small brown chest inside this tower
.complete 12292,1
>>Collect Cedar Chest
step
.goto Grizzly Hills,16.2,47.6
.target Samir
.turnin 12210 >> Turn in Troll Season!
.accept 11984 >> Accept Filling the Cages
step
.goto Grizzly Hills,16.4,48.3
.target Budd
>>Tell him it's time to play with the ice trolls
step
.goto Grizzly Hills,13.2,60.5
.macro Tag Troll,134400 >>/cast Tag Troll
>>Use Budd's pet bar skill Tag Troll to have him stun a troll
.use 35736
>>Use your Bounty Hunter's Cage on the stunned troll
.complete 11984,1
>>Capture a Live Ice Troll
step
.goto Grizzly Hills,16.2,47.6
.target Samir
.turnin 11984 >> Turn in Filling the Cages
step
.goto Grizzly Hills,16.4,47.8
.target Drakuru
.accept 11989 >> Accept Truce?
step
.goto Grizzly Hills,16.5,47.8
>>Click the Dull Carving Knife - It's a knife stuck in the side of this tree trunk
.collect 38083,1,11989 >> Collect 1 Dull Carving Knife
step
.goto Grizzly Hills,16.4,47.8
.use 38083
>>Use your Dull Carving Knife next to the yellow cage
.target Drakuru
>>Shake his hand
.complete 11989,1
>>Make a Blood Pact With Drakuru
step
.goto Grizzly Hills,16.4,47.8
.target Drakuru
.turnin 11989 >> Turn in Truce?
.accept 11990 >> Accept Vial of Visions
step
.goto Grizzly Hills,16,47.8
.target Ameenah
.complete 11990,1
>>Buy buy 1 Imbued Vial
step
.goto Grizzly Hills,14.6,45.3
>>Click the Hazewood Bushes - They look like small flower bushes on the ground around this area
.complete 11990,2
>>Collect Haze Leaf
step
.goto Grizzly Hills,15.2,40.3
>>Click a Waterweed - They look like big green bushes underwater around this area
.complete 11990,3
>>Collect Waterweed Frond
step
.goto Grizzly Hills,16.4,47.8
.target Drakuru
.turnin 11990 >> Turn in Vial of Visions
.accept 11991 >> Accept Subject to Interpretation
step
.goto Grizzly Hills,15.7,46.7
.target Prigmon
.accept 12484 >> Accept Scourgekabob
step
.goto Grizzly Hills,15.7,46.9
>>Click a Scourged Troll Mummy on the ground next to you - They look like mummies laying on the ground
.collect 38149,1,12484 >> Collect 1 Scourged Troll Mummy
step
.goto Grizzly Hills,16.9,48.3
.use 38149
>>Use your Scourged Troll Mummy next to the burning pile of mummies
.complete 12484,1
>>Burn a Mummified Carcass
step
.goto Grizzly Hills,16.7,48.3
.target Mack Fearsen
.turnin 12484 >> Turn in Scourgekabob
.accept 12029 >> Accept Seared Scourge
step
.goto Grizzly Hills,15.7,46.7
.target Prigmon
.accept 12483 >> Accept Shimmercap Stew
step
.goto Grizzly Hills,11.1,61.8
>>Click the Shimmering Snowcaps - They look like blue glowing mushrooms on the ground at the base of the trees around this area
.complete 12483,2
>>Collect Shimmering Snowcap
step
.goto Grizzly Hills,13.3,58.5
.mob Ice Serpents
>>Kill Ice Serpents
.complete 12483,1
>>Collect Ice Serpent Eye
.mob trolls
>>Kill trolls
.collect 35799,5,11991 >> Collect 5 Frozen Mojo
step
.goto Grizzly Hills,13.2,60.9
.use 35797
>>Use Drakuru's Elixir next to Drakuru's Brazier
.target Image of Drakuru
.turnin 11991 >> Turn in Subject to Interpretation
.accept 12007 >> Accept Sacrifices Must be Made
step
.goto Grizzly Hills,18.4,38.5
>>Click the Sweetroot plants - They look like aloe vera plants around this area
.complete 12483,3
>>Collect Sweetroot
step
.goto Grizzly Hills,14.5,38
.mob Warlord Zim'bo
>>Kill Warlord Zim'bo
.collect 35836,1,12007 >> Collect 1 Zim'bo's Mojo
step
.goto Grizzly Hills,17.9,36.5
>>Go up the huge stairs to 17.9,36.5
>>Click the Seer of Zeb'Halak statue - It's a huge blue glowing statue at the top of the stairs
.complete 12007,1
>>Collect Eye of the Prophets
step
.goto Grizzly Hills,17.4,36.4
.use 35797
>>Use Drakuru's Elixir next to Drakuru's Brazier
.target Image of Drakuru
.turnin 12007 >> Turn in Sacrifices Must be Made
.accept 12042 >> Accept Heart of the Ancients
step
.goto Grizzly Hills,16,29.9
>>Jump on the big rock and stand on it
.use 35908
>>Use Mack's Dark Grog and throw it at the trolls running around to the north
.complete 12029,1
>>Burn 20 Scourge Trolls
step
.goto Grizzly Hills,36.9,32.4
>>Go on top of the control station to 36.9,32.4
>>Click the Heart of the Ancients - It's a small pointed stone laying on the floor at the top of this control station, in a small room, next to a dead goblin
.turnin 12042 >> Turn in Heart of the Ancients
.accept 12802 >> Accept My Heart is in Your Hands
step
.goto Grizzly Hills,44.2,30.4
.mob Drakkari Defenders
>>Kill Drakkari Defenders
.collect 36743,5,12802 >> Collect 5 Desperate Mojo
step
.goto Grizzly Hills,45.0,28.4
.use 35797
>>Use Drakuru's Elixir next to Drakuru's Brazier
.target Image of Drakuru
.turnin 12802 >> Turn in My Heart is in Your Hands
.accept 12068 >> Accept Voices From the Dust
step
.goto Grizzly Hills,32.0,60.3,0.1
.hs >> Hearth to Amberpine Lodge
>>Hearth to Amberpine Lodge
step
.goto Grizzly Hills,31.8,60.2
.target Lieutenant Dumont
.turnin 12292 >> Turn in Local Support
.accept 12293 >> Accept Close the Deal
step
.goto Grizzly Hills,32.1,60
.target Master Woodsman Anderhol
.turnin 12215 >> Turn in Them or Us!
.accept 12217 >> Accept Eagle Eyes
step
.goto Grizzly Hills,34.8,55.6
.target Ivan
.turnin 12293 >> Turn in Close the Deal
.accept 12294 >> Accept A Tentative Pact
step
.goto Grizzly Hills,31.8,60.2
.target Lieutenant Dumont
.turnin 12294 >> Turn in A Tentative Pact
.accept 12295 >> Accept An Exercise in Diplomacy
step
.goto Grizzly Hills,32.4,59.9
.target Woodsman Drake
.accept 12222 >> Accept Secrets of the Flamebinders
.accept 12223 >> Accept Thinning the Ranks
step
.goto Grizzly Hills,33.6,79
.complete 12223,1
.mob Dragonflayer Huscarl
>>Kill Dragonflayer Huscarl
.mob Dragonflayer Flamebinders
>>Kill Dragonflayer Flamebinders
.complete 12222,1
>>Collect Flame-Imbued Talisman
step
.goto Grizzly Hills,32.4,59.9
.target Woodsman Drake
.turnin 12222 >> Turn in Secrets of the Flamebinders
.turnin 12223 >> Turn in Thinning the Ranks
.accept 12255 >> Accept The Thane of Voldrune
step
.goto Grizzly Hills,26.6,77.9
.target Flamebringer
.vehicle
>>Unchain and control Flamebringer
step
.goto Grizzly Hills,27.1,73
>>Fly to 27.1,73
>>Use the abilities on your hotbar
.complete 12255,1
.mob Thane Torvald Eriksson
>>Kill Thane Torvald Eriksson
step
.goto Grizzly Hills,32.4,59.9
.target Woodsman Drake
.turnin 12255 >> Turn in The Thane of Voldrune
step
.goto Grizzly Hills,34.4,58.3
.complete 12217,1
.mob Imperial Eagle
>>Kill Imperial Eagle
step
.goto Grizzly Hills,32.1,60
.target Master Woodsman Anderhol
.turnin 12217 >> Turn in Eagle Eyes
step
.goto Grizzly Hills,16.7,48.3
.target Mack Fearsen
.turnin 12029 >> Turn in Seared Scourge
step
.goto Grizzly Hills,15.7,46.7
.target Prigmon
.turnin 12483 >> Turn in Shimmercap Stew
.accept 12190 >> Accept Say Hello to My Little Friend
step
.goto Grizzly Hills,26.4,35.7
.target Envoy Ducal
.turnin 12295 >> Turn in An Exercise in Diplomacy
step
.goto Grizzly Hills,25.6,33.3
.target Katja
.accept 12307 >> Accept Wolfsbane Root
step
.goto Grizzly Hills,28.6,35.1
>>Click the Wolfsbane Roots - They look like spiraling green roots on the ground around this area
.complete 12307,1
>>Uproot 8 Wolfsbane Roots
step
.goto Grizzly Hills,25.6,33.3
.target Katja
.turnin 12307 >> Turn in Wolfsbane Root
step
.goto Grizzly Hills,26.5,35.8
.target Sergei
.accept 12299 >> Accept Northern Hospitality
step
.goto Grizzly Hills,24.3,34.5
.complete 12299,1
.mob Conquest Hold Marauder
>>Kill Conquest Hold Marauder
step
.goto Grizzly Hills,26.5,35.8
.target Sergei
.turnin 12299 >> Turn in Northern Hospitality
.accept 12300 >> Accept Test of Mettle
step
.goto Grizzly Hills,21.9,29.9
.mob Sergeant Bonesnap
>>Kill Sergeant Bonesnap
.complete 12300,1
>>Do the Test of Mettle
step
.goto Grizzly Hills,21.9,29.9
.target Captured Trapper
.turnin 12300 >> Turn in Test of Mettle
.accept 12302 >> Accept Words of Warning
step
.goto Grizzly Hills,26.5,31.8
.target Caged Prisoner
.turnin 12302 >> Turn in Words of Warning
.accept 12308 >> Accept Escape from Silverbrook
step
>>Follow the Caged Prisoner to a horse, click the horse to ride it
>>As you ride, use the abilities on your hotbar to fight and slow down the zombies
.complete 12308,1
>>Escape from Silverbrook
step
.goto Grizzly Hills,31.8,60.2
.target Lieutenant Dumont
.turnin 12308 >> Turn in Escape from Silverbrook
.accept 12310 >> Accept A Swift Response
step
.goto Grizzly Hills,36.3,67.9
.complete 12310,2
.mob Vladek
>>Kill Vladek
step
.goto Grizzly Hills,37,66.5
.complete 12310,1
.mob Silverbrook Hunter
>>Kill Silverbrook Hunter
>>Collect Mikhail's Journal
.use 36940
>>Click Mikhail's Journal in your bags
.accept 12105 >> Accept Descent into Darkness
step
.goto Grizzly Hills,31.8,60.2
.target Lieutenant Dumont
.turnin 12310 >> Turn in A Swift Response
.turnin 12105 >> Turn in Descent into Darkness
.accept 12109 >> Accept Report to Gryan Stoutmantle... Again
step
.goto Grizzly Hills,31.2,59.5
.target Hierophant Thayreen
.accept 12219 >> Accept The Failed World Tree
.accept 12220 >> Accept A Dark Influence
step
.goto Grizzly Hills,28.5,45.0
.goto Grizzly Hills,28.5,45.0,0.5
>>The path down to Vordrassil's Tears starts here
step
.goto Grizzly Hills,30.5,43.9
>>Go underground to 30.5,43.9
.use 37173
>>Use your Geomancer's Orb
.complete 12220,3
>>Use the Orb beneath Vordrassil's Tears
step
.goto Grizzly Hills,33.3,48.5
>>Go outside the tunnel to 33.3,48.5
.goto Grizzly Hills,33.3,48.5,0.5
>>The path down to Vordrassil's Limb starts here
step
.goto Grizzly Hills,32.2,45.8
>>Go underground to 32.2,45.8
.use 37173
>>Use your Geomancer's Orb
.complete 12220,2
>>Use the Orb beneath Vordrassil's Limb
step
.goto Grizzly Hills,40.7,52
>>Go outside the tunnel to 40.7,52
.goto Grizzly Hills,40.7,52.0,0.5
>>The path down to Vordrassil's Heart starts here
step
.goto Grizzly Hills,41.2,54.7
>>Go underground to 41.2,54.7
.use 37173
>>Use your Geomancer's Orb
.complete 12220,1
>>Use the Orb beneath Vordrassil's Heart
step
.goto Grizzly Hills,40.4,50.6
>>Go outside the tunnel to 40.4,50.6
.mob Entropic Oozes
>>Kill Entropic Oozes
.complete 12219,1
>>Collect Slime Sample
step
.goto Grizzly Hills,32.0,60.3,0.1
.hs >> Hearth to Amberpine Lodge
>>Hearth to Amberpine Lodge
step
.goto Grizzly Hills,31.2,59.5
.target Hierophant Thayreen
.turnin 12219 >> Turn in The Failed World Tree
.turnin 12220 >> Turn in A Dark Influence
.accept 12246 >> Accept A Possible Link
.accept 12247 >> Accept Children of Ursoc
step
.goto Grizzly Hills,66.9,62.4
.target Kodian
.complete 12247,2
>>Listen to Kodian's Story
step
.goto Grizzly Hills,63.6,57.9
.mob Redfang furbolgs
>>Kill Redfang furbolgs
.complete 12246,1
>>Collect Crazed Furbolg Blood
step
.goto Grizzly Hills,48.1,58.9
.target Orsonn
.complete 12247,1
>>Listen to Orsonn's Story
step
.goto Grizzly Hills,49.2,34.1
.target Emily
.accept 12027 >> Accept Mr. Floppy's Perilous Adventure
>>Escort Emily and protect Mr. Floppy
.complete 12027,1
>>Help Emily and Mr. Floppy return to the camp
step
.goto Grizzly Hills,59.1,26.5
.target Squire Percy
.accept 12414 >> Accept Mounting Up
step
.goto Grizzly Hills,59.1,26.5
.target Squire Walter
.turnin 12027 >> Turn in Mr. Floppy's Perilous Adventure
step
.goto Grizzly Hills,59.4,26
.target Captain Gryan Stoutmantle
.turnin 12109 >> Turn in Report to Gryan Stoutmantle... Again
.accept 12158 >> Accept Hollowstone Mine
.accept 11998 >> Accept Softening the Blow
step
.home Westfall Brigade Encampment >> Set your Hearthstone to Westfall Brigade Encampment
step
.goto Grizzly Hills,59.9,26.7
.target Samuel Clearbook
.fp Westfall Brigade, Grizzly Hills >> Get the Westfall Brigade Encampment flight path
step
.goto Grizzly Hills,55.1,23.4
.target Petrov
.turnin 12158 >> Turn in Hollowstone Mine
.accept 12159 >> Accept Souls at Unrest
step
.goto Grizzly Hills,54.9,23
.mob Undead Miners
>>Kill Undead Miners
.use 37932
>>Use your Miner's Lantern on their corpses
.complete 12159,1
>>Put 8 Miners at Rest
step
.goto Grizzly Hills,55.1,23.4
.target Petrov
.turnin 12159 >> Turn in Souls at Unrest
.accept 12160 >> Accept A Name from the Past
step
.goto Grizzly Hills,59.4,26
.target Captain Gryan Stoutmantle
.turnin 12160 >> Turn in A Name from the Past
step
.goto Grizzly Hills,59.2,26.2
.target Private Arun
.accept 12161 >> Accept Ruuna the Blind
step
.fly Amberpine Lodge, Grizzly Hills >> Fly to Amberpine Lodge
>>Fly to Amberpine Lodge
step
.goto Grizzly Hills,31.2,59.5
.target Hierophant Thayreen
.turnin 12246 >> Turn in A Possible Link
.turnin 12247 >> Turn in Children of Ursoc
.accept 12248 >> Accept Vordrassil's Sapling
.accept 12250 >> Accept Vordrassil's Seeds
step
.goto Grizzly Hills,44,47.9
.target Ruuna the Blind
.turnin 12161 >> Turn in Ruuna the Blind
.accept 12328 >> Accept Ruuna's Request
step
.goto Grizzly Hills,46.8,35.7
.mob Fern Feeder Moths
>>Kill Fern Feeder Moths
.complete 12328,1
>>Collect Gossamer Dust
step
.goto Grizzly Hills,44,47.9
.target Ruuna the Blind
.turnin 12328 >> Turn in Ruuna's Request
.accept 12327 >> Accept Out of Body Experience
step
.use 37661
>>Drink the Gossamer Potion in your bags next to Ruuna's Crystal Ball right next to you
.complete 12327,1
>>See the Vision from the Past
step
.goto Grizzly Hills,44,47.9
.target Ruuna the Blind
.turnin 12327 >> Turn in Out of Body Experience
.accept 12329 >> Accept Fate and Coincidence
step
.goto Grizzly Hills,50.5,46.0
.goto Grizzly Hills,50.5,46.0,0.5
>>The path down to Vordrassil's Sapling starts here
step
.goto Grizzly Hills,50.8,42.6
>>Follow the path down to 50.8,42.6
.use 37306
>>Use your Verdant Torch next to the tall tree
.complete 12248,1
>>Collect Vordrassil's Ashes
step
.goto Grizzly Hills,51.5,47.1
>>Go outside to 51.5,47.1
>>Click Vordrassil's Seeds - They look like brown pinecones sitting on the ground around this area
.complete 12250,1
>>Collect Vordrassil's Seed
step
.goto Grizzly Hills,57.5,41.3
>>Go outside to 57.5,41.3
.target Sasha
.turnin 12329 >> Turn in Fate and Coincidence
.accept 12134 >> Accept Sasha's Hunt
.accept 12330 >> Accept Anatoly Will Talk
step
.goto Grizzly Hills,60.4,40.2
.complete 12134,1
.mob Solstice Hunter
>>Kill Solstice Hunter
step
.goto Grizzly Hills,62.3,42
.use 37665
>>Use your Tranquilizer Dart on Tatjana
>>Click the horse to jump on it
.complete 12330,1
>>Deliver Tatjana
step
.goto Grizzly Hills,57.5,41.3
.target Sasha
.turnin 12134 >> Turn in Sasha's Hunt
.turnin 12330 >> Turn in Anatoly Will Talk
.accept 12411 >> Accept A Sister's Pledge
step
.goto Grizzly Hills,64.8,43.4
.target Anya
.turnin 12411 >> Turn in A Sister's Pledge
step
.goto Grizzly Hills,69.1,40.1
.target Hugh Glass
.accept 12279 >> Accept A Bear of an Appetite
.complete 11998,1
>>Buy buy Howlin' Good Moonshine
step
.goto Grizzly Hills,61.6,32.8
>>Click the Wild Carrots on the ground
.collect 37707,5,12414 >> Collect 5 Wild Carrot
step
.goto Grizzly Hills,60.3,25.4
.use 37708
>>Use your Stick on Highland Mustangs to ride them
>>Ride them back to Squire Percy at 59.1,26.6
.macro Hand Over Reins,134400 >>/cast Hand Over Reins
>>Use the Hand Over Reins ability on your hotbar to return the horses
.complete 12414,1
>>Return 5 Highland Mustangs
step
.goto Grizzly Hills,59.1,26.5
.target Squire Percy
.turnin 12414 >> Turn in Mounting Up
step
.goto Grizzly Hills,59.8,27.5
.target Brugar Stoneshear
.turnin 11998 >> Turn in Softening the Blow
.accept 12002 >> Accept Brothers in Battle
step
.goto Grizzly Hills,63.7,23.2
.target Fallen Earthen Warrior
.accept 11981 >> Accept Find Kurun!
step
.goto Grizzly Hills,64.3,19.8
>>Click the Battered Journal - It's a thick book sitting on the ground
.accept 11986 >> Accept The Damaged Journal
step
>>They look like torn pages that spawn all around this area on the ground
>>Click the Missing Journal Pages
.collect 35737,8,0 >> Collect 8 Missing Journal Page
.use 35739
>>Click the Incomplete Journal in your bags
.complete 11986,1
>>Collect Brann Bronzebeard's Journal
step
.goto Grizzly Hills,63.1,24.1
.complete 12002,1
.mob Runic Battle Golem
>>Kill Runic Battle Golem
step
.goto Grizzly Hills,61.5,23.9,0.5
>>The path up to Kurun starts here
step
.goto Grizzly Hills,65.8,17.8
>>Follow the road into the mountains around to 66,18
.target Kurun
.turnin 11981 >> Turn in Find Kurun!
.accept 11982 >> Accept Raining Down Destruction
step
.goto Grizzly Hills,66.1,13.8
>>Click the Boulders - They look like huge rocks on the ground around this area
.collect 35734,5,11982 >> Collect 5 Boulder
step
.goto Grizzly Hills,66.9,14.9
.use 35734
>>Use your Boulders on Iron Rune Shapers below
.complete 11982,1
>>Disrupt 5 Iron Dwarf Operations
step
.goto Grizzly Hills,65.8,17.8
.target Kurun
.turnin 11982 >> Turn in Raining Down Destruction
.accept 12070 >> Accept Rallying the Troops
step
.goto Grizzly Hills,68.3,10.1
.use 36764
>>Use your Shard of the Earth on Grizzly Hills Giants that are physically fighting another mob
.complete 12070,1
>>Rally 5 Grizzly Hills Giants
.complete 12070,2
>>Kill 5 Iron Rune Avengers that spawn
step
.goto Grizzly Hills,65.8,17.8
.target Kurun
.turnin 12070 >> Turn in Rallying the Troops
.accept 11985 >> Accept Into the Breach
step
.goto Grizzly Hills,70.2,13
>>Go down the hill and into the building to 70.2,13
.complete 11985,1
.mob Iron Thane Argrum
>>Kill Iron Thane Argrum
step
.goto Grizzly Hills,65.8,17.8
>>Go out of the building and up the path to 65.8,17.8
.target Kurun
.turnin 11985 >> Turn in Into the Breach
.accept 12081 >> Accept Gavrock
step
.goto Grizzly Hills,59.8,27.5
.target Brugar Stoneshear
.turnin 12002 >> Turn in Brothers in Battle
.accept 12003 >> Accept Uncovering the Tunnels
step
.goto Grizzly Hills,59.8,27.5
.target Torthen Deepdig
.turnin 11986 >> Turn in The Damaged Journal
.accept 11988 >> Accept The Runic Keystone
step
.goto Grizzly Hills,62.7,20.8
.complete 12003,1
>>Investigate the North Building
step
.goto Grizzly Hills,63.5,28.2
.complete 12003,3
>>Investigate the South Building
step
.goto Grizzly Hills,66.6,24.3
.complete 12003,2
>>Investigate the East Building
step
.goto Grizzly Hills,65.1,19.3
.mob iron dwarves
>>Kill iron dwarves
.complete 11988,1
>>Collect Runic Keystone Fragment
step
.goto Grizzly Hills,59.8,27.5
.target Brugar Stoneshear
.turnin 12003 >> Turn in Uncovering the Tunnels
.accept 12010 >> Accept The Fate of Orlond
step
.goto Grizzly Hills,59.8,27.5
.target Torthen Deepdig
.turnin 11988 >> Turn in The Runic Keystone
.accept 11993 >> Accept The Runic Prophecies
step
.goto Grizzly Hills,67.5,15.3
.target Surveyor Orlond
.turnin 12010 >> Turn in The Fate of Orlond
.accept 12014 >> Accept Steady as a Rock?
step
.goto Grizzly Hills,67.8,15.5
.mob Subterranean Threshers in the water
>>Kill Subterranean Threshers in the water
.complete 12014,2
>>Collect Portable Seismograph
step
.goto Grizzly Hills,68.5,16.2
>>Click the Third Rune Plate - It looks like a brown strip across a metal door in the wall
.complete 11993,3
>>Decipher the Third Prophecy
step
.goto Grizzly Hills,69,14.4
>>Click the First Rune Plate - It looks like a brown strip across a metal door in the wall
.complete 11993,1
>>Decipher the First Prophecy
step
.goto Grizzly Hills,70.2,14.7
>>Click the Second Rune Plate - It looks like a brown strip across a metal door in the wall
.complete 11993,2
>>Decipher the Second Prophecy
step
.goto Grizzly Hills,70.6,13.4
.use 35837
>>Use your Portable Seismograph next to this bridge in this spot
>>Click the Portable Seismograph that appears
.complete 12014,1
>>Collect Thor Modan Stability Profile
step
.goto Grizzly Hills,59.8,27.5
.target Brugar Stoneshear
.turnin 12014 >> Turn in Steady as a Rock?
.accept 12128 >> Accept Check Up on Raegar
step
.goto Grizzly Hills,59.8,27.5
.target Torthen Deepdig
.turnin 11993 >> Turn in The Runic Prophecies
step
.goto Grizzly Hills,59.5,26.3,0.5
.hs >> Hearth to Westfall Brigade Encampment
>>Hearth to Westfall Brigade Encampment
step
.fly Amberpine Lodge, Grizzly Hills >> Fly to Amberpine Lodge
>>Fly to Amberpine Lodge
step
.goto Grizzly Hills,31.2,59.5
.target Hierophant Thayreen
.turnin 12248 >> Turn in Vordrassil's Sapling
.turnin 12250 >> Turn in Vordrassil's Seeds
step
    >>Clean up. These only show if the quest is still in your log
    .abandon 12511 >> Abandon The Hills Have Us
    .abandon 12292 >> Abandon Local Support
    .abandon 12210 >> Abandon Troll Season!
    .abandon 12190 >> Abandon Say Hello to My Little Friend
    .abandon 12109 >> Abandon Report to Gryan Stoutmantle
    .abandon 12161 >> Abandon Ruuna the Blind
    .abandon 12414 >> Abandon Mounting Up
    .abandon 12279 >> Abandon A Bear of an Appetite
    .abandon 12128 >> Abandon Check Up on Raegar
    .abandon 12068 >> Abandon Voices From the Dust
    .abandon 12081 >> Abandon Gavrock
    .abandon 12248 >> Abandon Vordrassil's Sapling
    .abandon 12250 >> Abandon Vordrassil's Seeds
step
    #sticky
    +Level 80. That is the end of the 5x route. Dalaran has every class trainer, Cold Weather Flying and the Kirin Tor portals home: fly to Wyrmrest Temple, ride north into Crystalsong Forest and take the Violet Stand teleport crystal (15.7,42.5) up
]])
