-- GENERATED by tools/5x/build5x.py from Guides/7x/Alliance-Tanaris-7x.lua; edit the 7x file or the script.
-- RestedXP 5x route: Tanaris (WotLK 3.3.5a, Whitemane 5x). Arrive from Mudsprocket around
-- 48 with a mount. Gadgetzan hub: Waterspring Field and the Lost Rigger Cove pirates first
-- (the lowest-level quests), then the west and south (Noxious Lair, Dunemaul Compound,
-- Thistleshrub Valley, the Gahz'ridian ruins), then the Gaping Chasm hive. Zul'Farrak,
-- the Booty Bay chains, Tooga, the Feralas Screechers and the Darnassus turn-ins are skipped.
-- Ends on the road into Un'Goro Crater with Super Sticky and Bungle in the Jungle in the log.
local faction = UnitFactionGroup("player")
if faction == "Horde" then return end

RXPGuides.RegisterGuide([[
#wotlk
<< Alliance
#name 46-52 Tanaris (5x)
#version 1
#group RestedXP Alliance 5x
#next 52-58 Un'Goro (5x)
step
    #sticky
    #completewith next
    +Tanaris at 5x: you arrive around 46 and leave around 52. Everything runs from Gadgetzan, which has an inn and flight path but no class trainers. Druids get a Moonglade hop at the end of the second loop. The zone's level 43-46 quests go first so nothing decays
step
    .goto Thousand Needles,78.06,77.13,60,0
    .goto Tanaris,51.006,29.345
    >>Ride south-west out of Mudsprocket along the road: it climbs through the mountains into Thousand Needles and comes out at the Shimmering Flats. If you cannot find the pass, ride around by the Barrens road west of Shady Rest and take the Great Lift down. Cross the flats south into Tanaris and ride to Gadgetzan
    .fp Gadgetzan >> Get the Gadgetzan flight path
step
    .goto Tanaris,52.51,27.91
    .home >> Set your Hearthstone to Gadgetzan
    .bindlocation 976
step
    .goto Tanaris,50.210,27.483
.target Senior Surveyor Fizzledowser
>>Talk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .accept 992 >> Accept Gadgetzan Water Survey
step
    .goto Tanaris,52.462,28.514
.target Chief Engineer Bilgewhizzle
>>Talk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r
    .accept 1690 >> Accept Wastewander Justice
step
    .goto Tanaris,52.486,28.445
.target Spigot Operator Luglunket
>>Talk to |cRXP_FRIENDLY_Spigot Operator Luglunket|r
    .accept 1707 >> Accept Water Pouch Bounty
step
    .goto Tanaris,51.835,27.038
    >>Click the Wanted Poster
    .accept 2781 >> Accept WANTED: Caliph Scorpidsting
    .accept 2875 >> Accept WANTED: Andre Firebeard
step
    .goto Tanaris,52.819,27.401
.target Andi Lynn
>>Talk to |cRXP_FRIENDLY_Andi Lynn|r
    .accept 5863 >> Accept The Dunemaul Compound
step
    .goto Tanaris,51.80,28.66
.target Marin Noggenfogger
>>Talk to |cRXP_FRIENDLY_Marin Noggenfogger|r
    .accept 2605 >> Accept The Thirsty Goblin
step
    .goto Tanaris,51.56,26.75
.target Tran'rek
>>Talk to |cRXP_FRIENDLY_Tran'rek|r
    .accept 3362 >> Accept Thistleshrub Valley
step
    .goto Tanaris,39.016,29.244
    .use 8584 >> Ride west to the pond at Sandsorrow Watch and use the Untapped Dowsing Widget at the water. Two Centipaar Tunnelers spawn when it fills, kill them
    .complete 992,1 --Collect Tapped Dowsing Widget (x1)
step
    .goto Tanaris,50.210,27.483
    >>Ride back to Gadgetzan
.target Senior Surveyor Fizzledowser
>>Talk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .turnin 992 >> Turn in Gadgetzan Water Survey
    .accept 82 >> Accept Noxious Lair Investigation
step
    #sticky
    #label pouches
    >>Loot Wastewander Water Pouches from any Wastewander you kill
    .complete 1707,1 --Collect Wastewander Water Pouch (x5)
step
    .goto Tanaris,63.85,29.26,50,0
    .goto Tanaris,63.63,31.66,50,0
    .goto Tanaris,63.27,33.57,50,0
    .goto Tanaris,62.77,30.20,50,0
    .goto Tanaris,63.93,31.60
    >>Ride east into Waterspring Field and kill Wastewander Bandits and Thieves around the wells
    .complete 1690,1 --Kill Wastewander Bandit (x10)
    .complete 1690,2 --Kill Wastewander Thief (x10)
step
    .goto Tanaris,59.4,41.1,60,0
    .goto Tanaris,61.8,38.2,60,0
    .goto Tanaris,63.6,32.0,60,0
    .goto Tanaris,61.0,35.9,60,0
    .goto Tanaris,58.9,39.0,60,0
    .goto Tanaris,60.8,37.8
    >>Caliph Scorpidsting patrols through Waterspring Field with two Wastewander Rogues. Kill him and loot his head
    .unitscan Caliph Scorpidsting
    .complete 2781,1 --Collect Caliph Scorpidsting's Head (x1)
step
    .goto Tanaris,66.560,22.265
    >>Ride north-east to Steamwheedle Port
.target Haughty Modiste
>>Talk to |cRXP_FRIENDLY_Haughty Modiste|r
    .accept 8365 >> Accept Pirate Hats Ahoy!
step
    .goto Tanaris,67.058,23.891
.target Security Chief Bilgewhizzle
>>Talk to |cRXP_FRIENDLY_Security Chief Bilgewhizzle|r
    .accept 8366 >> Accept Southsea Shakedown
step
    #sticky
    #completewith pirates
    .use 9250 >> The pirates drop Pirate's Footlockers. Open them until a Ship Schedule drops, then right-click it to start a quest
    .collect 9250,1,2876,1 --Ship Schedule (1)
    .accept 2876 >> Accept Ship Schedules
step
    .goto Tanaris,71.10,42.86,70,0
    .goto Tanaris,71.33,46.05,70,0
    .goto Tanaris,73.09,45.30,70,0
    .goto Tanaris,74.17,46.28,70,0
    .goto Tanaris,73.76,47.79,65,0
    .goto Tanaris,74.62,47.73,50,0
    .goto Tanaris,75.17,45.84,60,0
    .goto Tanaris,71.90,44.92
    >>Ride south along the coast to Lost Rigger Cove. Kill ten of each pirate type and loot twenty Southsea Pirate Hats. Andre Firebeard is in the building at the back of the cove
    .complete 8366,1 --Kill Southsea Pirate (x10)
    .complete 8366,2 --Kill Southsea Freebooter (x10)
    .complete 8366,3 --Kill Southsea Dock Worker (x10)
    .complete 8366,4 --Kill Southsea Swashbuckler (x10)
    .complete 8365,1 --Collect Southsea Pirate Hat (x20)
step
    #label pirates
    .goto Tanaris,73.37,47.14
    >>Kill Andre Firebeard in the house and loot his head
    .complete 2875,1 --Collect Firebeard's Head (x1)
step
    .goto Tanaris,67.058,23.891
    >>Ride back north to Steamwheedle Port
.target Security Chief Bilgewhizzle
>>Talk to |cRXP_FRIENDLY_Security Chief Bilgewhizzle|r
    .turnin 8366 >> Turn in Southsea Shakedown
    .turnin 2875 >> Turn in WANTED: Andre Firebeard
    .turnin -2876 >> Turn in Ship Schedules
step
    .goto Tanaris,66.560,22.265
.target Haughty Modiste
>>Talk to |cRXP_FRIENDLY_Haughty Modiste|r
    .turnin 8365 >> Turn in Pirate Hats Ahoy!
step
    #completewith next
    .hs >> Hearth to Gadgetzan
step
    #requires pouches
    .goto Tanaris,52.486,28.445
.target Spigot Operator Luglunket
>>Talk to |cRXP_FRIENDLY_Spigot Operator Luglunket|r
    .turnin 1707 >> Turn in Water Pouch Bounty
step
    .goto Tanaris,52.462,28.514
.target Chief Engineer Bilgewhizzle
>>Talk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r
    .turnin 1690 >> Turn in Wastewander Justice
    .turnin 2781 >> Turn in WANTED: Caliph Scorpidsting
    .accept 1691 >> Accept More Wastewander Justice
step
    .goto Tanaris,58.75,39.34,60,0
    .goto Tanaris,58.72,36.54,60,0
    .goto Tanaris,60.07,37.31,60,0
    .goto Tanaris,60.76,32.67,60,0
    .goto Tanaris,63.57,37.80,60,0
    .goto Tanaris,63.89,39.86,60,0
    .goto Tanaris,65.03,39.49,60,0
    .goto Tanaris,65.41,36.62
    >>Ride back east to Waterspring Field. Kill Wastewander Rogues (stealthed), Assassins and Shadow Mages around the southern wells
    .complete 1691,1 --Kill Wastewander Rogue (x8)
    .complete 1691,2 --Kill Wastewander Assassin (x6)
    .complete 1691,3 --Kill Wastewander Shadow Mage (x10)
step
    .goto Tanaris,52.462,28.514
    >>Ride back to Gadgetzan
.target Chief Engineer Bilgewhizzle
>>Talk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r
    .turnin 1691 >> Turn in More Wastewander Justice
step
    #sticky
    #completewith next
    +Loop two: south to the Broken Pillar, then west through the Noxious Lair, the Dunemaul Compound and Thistleshrub Valley, back east through the Southmoon and Eastmoon ruins, and hearth from the Broken Pillar
step
    .goto Tanaris,52.707,45.923
    >>Ride south to the Broken Pillar
.target Marvon Rivetseeker
>>Talk to |cRXP_FRIENDLY_Marvon Rivetseeker|r
    .accept 3161 >> Accept Gahz'ridian
step
    .goto Tanaris,35.68,39.78,70,0
    .goto Tanaris,36.55,41.98,70,0
    .goto Tanaris,35.59,44.08,70,0
    .goto Tanaris,35.60,48.79,70,0
    .goto Tanaris,31.70,49.12,70,0
    .goto Tanaris,30.83,46.10
    >>Ride west to the Noxious Lair. Kill any Centipaar silithid on the surface for five insect parts. Do not go into the hive, and pull one at a time, the Swarmers summon adds
    .complete 82,1 --Collect Centipaar Insect Parts (x5)
step
    .goto Tanaris,37.83,56.94,70,0
    .goto Tanaris,38.64,51.83,70,0
    .goto Tanaris,41.04,51.18,70,0
    .goto Tanaris,42.63,55.10
    >>Ride south into the Dunemaul Compound. Kill Brutes and Enforcers
    .complete 5863,1 --Kill Dunemaul Brute (x10)
    .complete 5863,2 --Kill Dunemaul Enforcer (x10)
step
    .goto Tanaris,41.50,57.81
    >>Kill Gor'marok the Ravager at the back of the compound. He enrages, keep your health up
    .complete 5863,3 --Kill Gor'marok the Ravager (x1)
step
    .goto Tanaris,28.57,66.42,60,0
    .goto Tanaris,28.51,63.22,60,0
    .goto Tanaris,30.21,63.85,60,0
    .goto Tanaris,30.45,66.15
    >>Ride south-west into Thistleshrub Valley. Kill Gnarled Thistleshrubs and Rootshapers, and Dew Collectors until a Laden Dew Gland drops (low drop rate, keep killing Collectors)
    .complete 3362,1 --Kill Gnarled Thistleshrub (x8)
    .complete 3362,2 --Kill Thistleshrub Rootshaper (x8)
    .complete 2605,1 --Collect Laden Dew Gland (x1)
step
    #completewith next
    .use 9978 >> Equip the Gahz'ridian Detector in your head slot, the ornaments then show on the minimap
step
    .goto Tanaris,41.04,71.69,70,0
    .goto Tanaris,39.66,73.51,70,0
    .goto Tanaris,46.01,65.13,70,0
    .goto Tanaris,47.81,64.83
    >>Ride east to the Southmoon and Eastmoon ruins. With the detector equipped, loot the Gahz'ridian piles of sand shown on your minimap until you have thirty ornaments
    .complete 3161,1 --Collect Gahz'ridian Ornament (x30)
step
    #sticky
    #completewith next
    +Put your normal helmet back on
step
    .goto Tanaris,52.707,45.923
    >>Ride north-east back to the Broken Pillar
.target Marvon Rivetseeker
>>Talk to |cRXP_FRIENDLY_Marvon Rivetseeker|r
    .turnin 3161 >> Turn in Gahz'ridian
step << Druid
    .goto Moonglade,52.53,40.57
    >>Cast Teleport: Moonglade and train from Loganaar in Nighthaven, then hearth to Gadgetzan from here
    .trainer >> Train your class spells
step
    #completewith next
    .hs >> Hearth to Gadgetzan
step
    .goto Tanaris,50.886,26.963
.target Alchemist Pestlezugg
>>Talk to |cRXP_FRIENDLY_Alchemist Pestlezugg|r
    .turnin 82 >> Turn in Noxious Lair Investigation
step
    .goto Tanaris,52.819,27.401
.target Andi Lynn
>>Talk to |cRXP_FRIENDLY_Andi Lynn|r
    .turnin 5863 >> Turn in The Dunemaul Compound
step
    .goto Tanaris,51.56,26.75
.target Tran'rek
>>Talk to |cRXP_FRIENDLY_Tran'rek|r
    .turnin 3362 >> Turn in Thistleshrub Valley
step
    .goto Tanaris,51.80,28.66
.target Marin Noggenfogger
>>Talk to |cRXP_FRIENDLY_Marin Noggenfogger|r
    .turnin 2605 >> Turn in The Thirsty Goblin
    .accept 2606 >> Accept In Good Taste
step
    .goto Tanaris,51.05,26.87
.target Sprinkle
>>Talk to |cRXP_FRIENDLY_Sprinkle|r
    .turnin 2606 >> Turn in In Good Taste
step
    .goto Tanaris,50.210,27.483
.target Senior Surveyor Fizzledowser
>>Talk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .accept 10 >> Accept The Scrimshank Redemption
step
    .goto Tanaris,54.63,70.75,15,0
    .goto Tanaris,54.451,69.778,20,0
    .goto Tanaris,53.705,71.367,20,0
    .goto Tanaris,54.322,72.07,20,0
    .goto Tanaris,55.64,71.506,20,0
    .goto Tanaris,56.513,70.824,20,0
    .goto Tanaris,55.956,71.164
    >>Ride south to the Gaping Chasm and go down into the hive through the entrance on its north side. Scrimshank's Surveying Gear lies on the ground inside, near the corpse. Pull carefully, the tunnels are full of silithid
    .complete 10,1 --Collect Scrimshank's Surveying Gear (x1)
step
    .goto Tanaris,54.69,70.62,10
    >>Leave the hive the way you came in
step
    .goto Tanaris,60.235,64.714
    .use 8623 >> Only if an OOX-17/TN Distress Beacon dropped for you from a scorpid or basilisk: right-click it to start the quest, then hand it to the robot east of the chasm. Do not start his escort
    .collect 8623,1,351,1 --OOX-17/TN Distress Beacon (1)
    .accept 351 >> Accept Find OOX-17/TN!
    .itemcount 8623,1
step
    .isOnQuest 351
    .goto Tanaris,60.235,64.714
.target Homing Robot OOX-17/TN
>>Talk to |cRXP_FRIENDLY_Homing Robot OOX-17/TN|r
    .turnin 351 >> Turn in Find OOX-17/TN!
step
    .goto Tanaris,50.210,27.483
    >>Ride back north to Gadgetzan
.target Senior Surveyor Fizzledowser
>>Talk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .turnin 10 >> Turn in The Scrimshank Redemption
    .accept 110 >> Accept Insect Part Analysis
step
    .goto Tanaris,50.886,26.963
.target Alchemist Pestlezugg
>>Talk to |cRXP_FRIENDLY_Alchemist Pestlezugg|r
    .turnin 110 >> Turn in Insect Part Analysis
    .accept 113 >> Accept Insect Part Analysis
step
    .goto Tanaris,50.210,27.483
.target Senior Surveyor Fizzledowser
>>Talk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .turnin 113 >> Turn in Insect Part Analysis
step
    .goto Tanaris,50.886,26.963
    >>These two are completed in Un'Goro Crater and turned in here when you hearth back
.target Alchemist Pestlezugg
>>Talk to |cRXP_FRIENDLY_Alchemist Pestlezugg|r
    .accept 4496 >> Accept Bungle in the Jungle
step
    .goto Tanaris,51.56,26.75
.target Tran'rek
>>Talk to |cRXP_FRIENDLY_Tran'rek|r
    .accept 4504 >> Accept Super Sticky
step
    >>Clean up before leaving Tanaris. These only show if the quest is still in your log
    .abandon 2876 >> Abandon Ship Schedules
    .abandon 351 >> Abandon Find OOX-17/TN!
    .abandon 2605 >> Abandon The Thirsty Goblin if the gland never dropped
    .abandon 2606 >> Abandon In Good Taste
step
    #sticky
    #completewith next
    +Tanaris is done around level 54. Keep your hearthstone on Gadgetzan: the Un'Goro chapter hearths back here to turn in Bungle in the Jungle and Super Sticky
step
    .goto Tanaris,26.98,56.09,125,0
    .goto Un'Goro Crater,71.63,75.95
    .zone Un'Goro Crater >> Ride south-west along the road out of Tanaris and down the ramp into Un'Goro Crater
]])
